;;; tmux-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from tmux-mode.el

(autoload 'tmux-mode "tmux-mode" "\
Major mode for tmux configuration files.

\\{tmux-mode-map}

(fn)" t)
(add-to-list 'auto-mode-alist (cons "\\.?tmux\\.conf\\'" 'tmux-mode))
(register-definition-prefixes "tmux-mode" '("tmux-mode-"))

;;; End of scraped data

(provide 'tmux-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; tmux-mode-autoloads.el ends here
