function OptionsController(){function e(a){h={};k={};z={};for(var c in q){var b=q[c],d=document.getElementById(b);h[b]=a.options[b];k[a.options[b]]=b;d=new ShortcutSetter(d,a.options[b],"optionsPage",function(a,b){var c=a.id;if(k[b]){if(k[b]==c)return!1;r=z[k[b]];r.showConflict();return{conflict:!0}}if(/(\||^)27(\||$)/.test(b)&&"closeWebClipperShortcut"!==c)return{noEsc:!0};l();var d={};d[c]=b;console.log("Sending options change:");console.log(d);Browser.sendToExtension({name:"main_setOption",options:d});
Browser.sendToExtension({name:"bounceToAll",message:{name:"updateKeyboardShortcut",oldShortcut:h[c],shortcut:b,shortcutName:c}});delete k[h[c]];k[b]=c;h[c]=b;return!1},function(){if(E)return!0;E=!0;return!1},function(){r&&(r.removeConflict(),r=null)},function(){return document.getElementById("shortcutsContainer").classList.contains("disabled")},function(a){return m[a]});z[b]=d}}function n(a){if(a=this.id){l();var c={};c[a]=this.checked;"useSearchHelper"==a?g&&Persistent.set(g.userId+"_turnedOffSearchHelper",
!0):"enableKeyboardShortcuts"==a&&(this.checked?document.getElementById("shortcutsContainer").classList.remove("disabled"):document.getElementById("shortcutsContainer").classList.add("disabled"),Browser.sendToExtension({name:"bounceToAll",message:{name:"receiveKeyboardShortcutsEnabled",keyboardShortcutsEnabled:this.checked}}));Browser.sendToExtension({name:"main_setOption",options:c})}p()}function A(a){if(a=this.id){l();var c={};c[a]=this.options[this.selectedIndex].value;Browser.sendToExtension({name:"main_setOption",
options:c})}p()}function J(a){if(a=this.id){l();var c={};c[a]=this.value;console.log("Sending options change:");console.log(c);Browser.sendToExtension({name:"main_setOption",options:c})}p()}function K(){var a=this.name;if(a){l();var c={};c[a]=this.value;"notebookSelection"==a&&("smartFiling"===this.value&&g&&g.bizAuthenticationToken?document.getElementById("bizSmartFilingCheckbox").style.display="block":(document.getElementById("bizSmartFilingCheckbox").style.display="","alwaysStartIn"===this.value&&
A.call(document.getElementById("startNotebook"))));Browser.sendToExtension({name:"main_setOption",options:c})}p()}function l(){window.setTimeout(function(){document.querySelector("#savingContainer").className="invisible"},500);document.querySelector("#savingContainer").className="visible"}function p(){var a=document.getElementById("optionsContainer").scrollHeight;document.getElementsByClassName("pinch")[0].style.height=a+"px";Browser.sendToExtension({name:"bounce",message:{name:"setOptionsHeight",
height:266+a}})}function L(a,c){F&&0>["INPUT","TEXTAREA"].indexOf(c.nodeName)&&"true"!==c.contentEditable&&Browser.sendToExtension({name:"bounce",message:{name:"duplicateKeyboardShortcut",keycode:a}})}function M(a,c){0>["INPUT","TEXTAREA"].indexOf(c.nodeName)&&"true"!==c.contentEditable&&Browser.sendToExtension({name:"bounce",message:{name:"duplicateKeyboardShortcut",keycode:a}})}function G(a,c,b){function d(a){if("OPTION"===a.nodeName)return a.innerText;if("OPTGROUP"===a.nodeName)return a.label}
c=document.getElementById("startNotebook");for(b=0;b<a.notebooks.length;b++){var f=document.createElement("option");f.text=a.notebooks[b].name;a.notebooks[b].owner&&(f.text+=" ("+a.notebooks[b].owner+")");f.value=a.notebooks[b].guid;a.notebooks[b].stack?(s[a.notebooks[b].stack]||(s[a.notebooks[b].stack]=document.createElement("optgroup"),s[a.notebooks[b].stack].label=a.notebooks[b].stack,CommonSelector.binaryInsert(c,d,s[a.notebooks[b].stack])),CommonSelector.binaryInsert(s[a.notebooks[b].stack],
d,f)):CommonSelector.binaryInsert(c,d,f);a.notebooks[b].defaultNotebook&&(B=f);C&&C===a.notebooks[b].guid&&(H=f.selected=!0)}B&&!H&&(B.selected=!0)}var E=!1,F=!0;window.addEventListener("DOMContentLoaded",function(){document.getElementById("signOut").addEventListener("click",function(){Browser.sendToExtension({name:"LOGOUT"});Browser.sendToExtension({name:"trackEvent",category:"Account",action:"sign_out",endSession:!0})});document.getElementById("resetShortcuts").addEventListener("click",function(){l();
Browser.sendToExtension({name:"main_clearOptions",options:q})});document.getElementById("done").addEventListener("click",function(){Browser.sendToExtension({name:"bounce",message:{name:"hideOptions",authed:!!g}})});Browser.sendToExtension({name:"getPersistentValue",key:"charCodeCache"})});Browser.addMessageHandlers({logoutCallback:function(){location.reload()},options_config:function(a){if(a.options){GlobalUtils.localize(document.body);GlobalUtils.localize(document.getElementsByTagName("title")[0]);
for(var c in v){var b=v[c],d=document.getElementById(b);d.checked=a.options[b];"enableKeyboardShortcuts"==b&&(d.checked||document.getElementById("shortcutsContainer").classList.add("disabled"));d.addEventListener("change",n)}for(c in w){b=w[c];d=document.getElementById(b);if("startNotebook"===b)g&&(C=a.options[b],Browser.sendToExtension({name:"getNotebooks",page:"op"}));else for(var b=a.options[b],f=0;f<d.options.length;f++)if(d.options[f].value==b){d.selectedIndex=f;break}d.addEventListener("change",
A)}for(c in x)b=x[c],d=document.getElementById(b),d.value=a.options[b],d.addEventListener("change",J);for(c in y)for(b=y[c],"notebookSelection"===b&&"smartFiling"===a.options[b]&&g&&g.bizAuthenticationToken&&(document.getElementById("bizSmartFilingCheckbox").style.display="block"),d=document.getElementsByName(b),f=0;f<d.length;f++)d.item(f).value==a.options[b]&&(d.item(f).checked=!0),d.item(f).addEventListener("change",K);e(a);p()}},options_isAuthenticated:function(a){a&&a.auth&&(g=a.auth,document.body.classList.add("loggedIn"),
document.getElementById("username").innerText=g.email);a={};for(var c in v)a[v[c]]=!1;for(c in w)a[w[c]]=!1;for(c in x)a[x[c]]=!1;for(c in q)a[q[c]]=!1;for(c in y)a[y[c]]=!1;Browser.sendToExtension({name:"main_getConfig",options:a,returnName:"options_config"})},optionsCleared:function(a,c,b){c=[];b=[];var d=[],f;for(f in a.options)a.options[f]!==h[f]&&(c.push(h[f]),b.push(a.options[f]),d.push(f));e(a);Browser.sendToExtension({name:"bounceToAll",message:{name:"updateKeyboardShortcut",oldShortcut:c,
shortcut:b,shortcutName:d}})},op_receivePersonalNotebooks:G,op_receiveSharedNotebooks:G,op_setKeyboardHandlers:function(a,c,b){F=a.enabled;if(a.handlers){c={};for(var d in a.handlers)for(b=0;b<a.handlers[d].length;b++)c[a.handlers[d][b]]="closeWebClipperShortcut"===d?M:L;Browser.addKeyboardHandlers(c)}},op_setPinchHeight:function(a,c,b){document.getElementsByClassName("pinch")[0].style.height=a.totalHeight-266+"px"},receivePersistentValue:function(a,c,b){"charCodeCache"==a.key&&(m=a.value||{},Browser.sendToExtension({name:"main_isAuthenticated",
type:"options"}))}});var v="smartFilingTags alwaysTagWith useSearchHelper simulateSimplifiedChinese useStage enableKeyboardShortcuts bizSmartFilingEnabled includeDebugInfo".split(" "),w=["startNotebook","clipAction","readingSpeed","voice"],x=["alwaysTags","insecureProto","secureProto","overrideServiceURL","relatedNotesContext"],y=["notebookSelection","defaultClipAction","afterClip"],q="startWebClipperShortcut closeWebClipperShortcut previewArticleShortcut previewFullPageShortcut previewUrlShortcut selectionModeShortcut takeScreenshotShortcut clearlyShortcut pdfShortcut emailShortcut expandArticleShortcut contractArticleShortcut moveArticleUpShortcut moveArticleDownShortcut selectNotebookShortcut addTagsShortcut saveShortcut selectAllMarkupShortcut arrowShortcut textShortcut rectangleShortcut roundedRectangleShortcut ellipseShortcut lineShortcut markerShortcut highlighterShortcut stampShortcut pixelateShortcut cropShortcut zoomInShortcut zoomOutShortcut zoomToFitShortcut zoomToOriginalShortcut undoShortcut redoShortcut".split(" "),
h={},k={},z={},r,t,m,g=null;window.addEventListener("keydown",function(a){m&&(65>a.keyCode||90<a.keyCode)&&(t=a.keyCode)},!0);window.addEventListener("keypress",function(a){m&&t&&(t!=a.charCode&&(m[t]=a.charCode,Browser.sendToExtension({name:"setPersistentValue",key:"charCodeCache",value:m})),t=null)});window.addEventListener("keydown",function(a){event.keyCode==I[u]?u++:u=0;u==I.length&&(u=0,"none"==document.getElementById(D).style.display?document.getElementById(D).style.display="block":document.getElementById(D).style.display=
"none",p())});var I=[38,38,40,40,37,39,37,39,66,65],u=0,D="developerContainer",s={},C=null,B=null,H=!1;Object.preventExtensions(this)}Object.preventExtensions(OptionsController);var optionsController=new OptionsController;
window.addEventListener("DOMContentLoaded",function(){SAFARI&&document.body.classList.add("safari");/iframe/.test(document.location.hash)&&document.body.classList.add("iframe");Browser.addMessageHandlers({options_config:function(e){if(e.bootstrapInfo&&e.bootstrapInfo.name){e.bootstrapInfo.name.match(/china/i)&&document.body.classList.add("china");e="https://"+e.bootstrapInfo.serviceHost;document.getElementById("copyright").innerHTML=Browser.i18n.getMessage("copyright",[e]);document.getElementById("logDescription").innerHTML=
Browser.i18n.getMessage("options_eventLogDescription",[e+"/privacy"]);e=document.getElementsByClassName("tab");for(var n=0;n<e.length;n++)e.item(n).addEventListener("click",function(){var e=document.querySelector(".tab.pressed");e&&(e.className=e.className.replace(/\s*pressed/g,""));e=document.querySelector(".pinch");e.className=e.className.replace(/\s*(options|shortcuts|legal)/g,"");this.className+=" pressed";"optionsTab"==this.id?e.className+=" options":"shortcutsTab"==this.id?e.className+=" shortcuts":
"legalTab"==this.id&&(e.className+=" legal")});/shortcuts/.test(document.location.hash)&&document.getElementById("shortcutsTab").click()}},receivePersistentValue:function(e,n,A){"EVERNOTE_VERSION"==e.key&&(document.getElementById("version").innerText=e.value+" ("+BUILD_VERSION+"/"+SKITCH_BUILD_VERSION+")")}});Browser.sendToExtension({name:"main_getConfig",bootstrapInfo:{name:null,serviceHost:null},returnName:"options_config"});Browser.sendToExtension({name:"getPersistentValue",key:"EVERNOTE_VERSION"})});
window.addEventListener("error",function(e){log.error(JSON.stringify(e))});
