;;; docopt-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from docopt.el

(autoload 'docopt-parse "docopt" "\
Parse the program from S.

(fn S)")
(autoload 'docopt-shell-command "docopt" "\
Run the shell COMMAND with the --help option and parse the result as a program.

(fn COMMAND)")
(autoload 'docopt-eval-ast "docopt" "\
Parse the argument vector from S using the PROGRAM.

(fn PROGRAM S)")
(autoload 'docopt-eval "docopt" "\
Parse the argument vector from S using the PROGRAM.

(fn PROGRAM S)")
(autoload 'docopt "docopt" "\
Invoke the transient command for the shell COMMAND.

(fn COMMAND)" t)
(register-definition-prefixes "docopt" '("docopt-invalid-program"))


;;; Generated autoloads from docopt-abbrev.el

(register-definition-prefixes "docopt-abbrev" '("docopt-abbrev-"))


;;; Generated autoloads from docopt-analyzer.el

(register-definition-prefixes "docopt-analyzer" '("docopt-analyze"))


;;; Generated autoloads from docopt-argv.el

(register-definition-prefixes "docopt-argv" '("docopt-"))


;;; Generated autoloads from docopt-ast.el

(register-definition-prefixes "docopt-ast" '("docopt-"))


;;; Generated autoloads from docopt-parser.el

(register-definition-prefixes "docopt-parser" '("docopt-"))


;;; Generated autoloads from docopt-transient.el

(register-definition-prefixes "docopt-transient" '("docopt-"))


;;; Generated autoloads from docopt-util.el

(register-definition-prefixes "docopt-util" '("docopt-"))

;;; End of scraped data

(provide 'docopt-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; docopt-autoloads.el ends here
