" gvim initialization

source $HOME/.vim/vimrc
set laststatus          =2

set guicursor           =a:block

"set guifont            =Terminal\ 14
"set guifont            =Monospace\ Regular\ 10
"set guifont            =Inconsolata\ Regular\ 10
set guifont             =Ubuntu\ Mono\ Regular\ 12

set guioptions         +=a
set guioptions         -=b
set guioptions         -=c
set guioptions         +=g
set guioptions         -=h
set guioptions         -=l
set guioptions         -=L
set guioptions         -=m
set guioptions         -=P
set guioptions         -=r
set guioptions         -=R
set guioptions         +=t
set guioptions         -=T

if &diff
    set columns=999 lines=999
else
    set columns=90  lines=36
endif

set mousefocus

"end gvimrc
