;;; uniquify-files-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (directory-file-name
                         (or (file-name-directory #$) (car load-path))))



;;; Generated autoloads from uniquify-files.el

(autoload 'uniq-file-read "uniquify-files" "\
For `project-read-file-name-function'.

(fn PROMPT ALL-FILES &optional PREDICATE HIST DEFAULT)" nil nil)
(register-definition-prefixes "uniquify-files" '("uniq-file-"))


;;; Generated autoloads from uniquify-files-test.el

(register-definition-prefixes "uniquify-files-test" '("test-uniq-file-hilit" "uft-"))

;;; End of scraped data

(provide 'uniquify-files-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; coding: utf-8-emacs-unix
;; End:

;;; uniquify-files-autoloads.el ends here
