#!/bin/sh

# $Id$
# $Source$

# uptimes host...

PATH=/usr/bin:/usr/ucb

if [ $# -eq 0 -o X$1 = 'X-?' ]; then
    echo 1>&2 usage: `basename $0` hostname...
    exit 1
fi

for host in "$@"; do
    if [ `expr length $host` -ge 8 ]; then
        echo -n $host':'
    else
        echo -n $host'	:'      #'tab-colon'
    fi
    rsh $host uptime
done

