;;; string-edit-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (directory-file-name
                         (or (file-name-directory #$) (car load-path))))



;;; Generated autoloads from string-edit.el

(autoload 'string-edit-at-point "string-edit" "\
Pop up a buffer to edit the string at point.
This saves you from needing to manually escape characters." t nil)
(register-definition-prefixes "string-edit" '("se/" "string-edit-"))

;;; End of scraped data

(provide 'string-edit-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; coding: utf-8-emacs-unix
;; End:

;;; string-edit-autoloads.el ends here
