;;; gnat-compiler-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from gnat-alire.el

(autoload 'create-alire-prj "gnat-alire" "\
Return an initial wisi project for the current Alire workspace.

(fn &key NAME GPR-FILE COMPILE-ENV FILE-ENV XREF-LABEL)")
(register-definition-prefixes "gnat-alire" '("alire-get-env"))


;;; Generated autoloads from gnat-compiler.el

(autoload 'create-gnat-compiler "gnat-compiler" "\


(fn &key GPR-FILE RUN-BUFFER-NAME PROJECT-PATH TARGET RUNTIME GNAT-STUB-OPTS GNAT-STUB-CARGS)")
(register-definition-prefixes "gnat-compiler" '("gnat"))


;;; Generated autoloads from gnat-xref.el

(autoload 'create-gnat-xref "gnat-xref" "\


(fn &key GPR-FILE RUN-BUFFER-NAME PROJECT-PATH TARGET RUNTIME GNAT-STUB-OPTS GNAT-STUB-CARGS)")
(register-definition-prefixes "gnat-xref" '("gnat-"))

;;; End of scraped data

(provide 'gnat-compiler-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; gnat-compiler-autoloads.el ends here
