function NotebookSelector(k,n,v){function B(b){var a=document.createElement("div");a.classList.add("nbStack");var c=document.createElement("h3");c.innerText=b;c.title=c.innerText;a.appendChild(c);w(a);return a}function C(b,a,c,e,f){f-=1;for(b=b.toLowerCase();e<=f;){for(var d=e+Math.floor((f-e)/2),g=c[d],r=0;r<(a?a.length:0);r++)g=g[a[r]];if(b<g.innerText.toLowerCase())f=d-1;else if(b>g.innerText.toLowerCase())e=d+1;else return d}return-1}function x(){var b=k.classList.contains("nbOpen");k.classList.remove("nbOpen");
h.value="";y();v();return b}function w(b,a){function c(a){if(a.classList.contains("nbStack"))return a.firstElementChild.innerText;if(a.classList.contains("nbNotebook"))return a.innerText}var e=d;a&&(e=d.querySelectorAll(".nbStack"),e=e[C(a,["firstElementChild"],e,0,e.length)]||d,e===d&&(e=B(a)));a?CommonSelector.binaryInsert(e,c,b,1):CommonSelector.binaryInsert(e,c,b)}function z(b){for(var a=0;a<l.length;a++)if(0>l[a].indexOf(b))return!1;return!0}function s(){k.classList.add("nbOpen");h.focus();setTimeout(function(){g.scrollIntoViewIfNeeded()},
50);v()}function y(){for(var b=d.querySelectorAll(".nbNotebook.nbHover"),a=0;a<b.length;a++)b[a].classList.remove("nbHover");if(b=h.value.trim()){b=b.split(/\s+/);l=[];for(a=0;a<b.length;a++){for(var c=p.getMatching(b[a]),e=[],f=0;f<c.length;f++)e=e.concat(c[f][1]);l.push(e)}b=d.querySelectorAll(".nbNotebook");for(a=0;a<b.length;a++)z(b[a])?b[a].classList.remove("nbHidden"):b[a].classList.add("nbHidden");d.classList.add("nbSearchOn");(a=d.querySelector(".nbNotebook:not(.nbHidden)"))&&a.classList.add("nbHover")}else{b=
d.querySelectorAll(".nbHidden");for(a=0;a<b.length;a++)b[a].classList.remove("nbHidden");d.classList.remove("nbSearchOn")}}function t(b){g&&g.classList.remove("nbSelectedNotebook");b.classList.add("nbSelectedNotebook");g=b;c.innerText=b.innerText;c.title=c.innerText;c.setAttribute("guid",g.getAttribute("guid"));g.classList.contains("nbBusinessNotebook")?(c.classList.remove("nbSelectedLinked"),c.classList.add("nbSelectedBusiness"),c.removeAttribute("globalId"),c.removeAttribute("shardId"),n({notebookType:GlobalUtils.NOTEBOOK_TYPE_BUSINESS})):
g.classList.contains("nbLinkedNotebook")?(c.classList.remove("nbSelectedBusiness"),c.classList.add("nbSelectedLinked"),c.setAttribute("globalId",g.getAttribute("globalId")),c.setAttribute("shardId",g.getAttribute("shardId")),n({notebookType:GlobalUtils.NOTEBOOK_TYPE_LINKED})):(c.classList.remove("nbSelectedBusiness"),c.classList.remove("nbSelectedLinked"),c.removeAttribute("globalId"),c.removeAttribute("shardId"),n({notebookType:GlobalUtils.NOTEBOOK_TYPE_PERSONAL}));g.hasAttribute("noShareNotes")?
c.setAttribute("noShareNotes",""):c.removeAttribute("noShareNotes");g.hasAttribute("default")?c.setAttribute("default",""):c.removeAttribute("default")}function u(){k.classList.contains("nbOpen")?x():s()}function D(b){var a=h.value.trim();if(a)for(var a=a.split(/\s+/),c=0;c<a.length;c++)RegExp("(?:\\s|^)"+a[c],"i").test(b.firstElementChild.innerText)&&(l[c]||l.push([]),l[c].push(b))}var g,p=new Trie,l=[],c=document.createElement("div"),m=document.createElement("div"),A=document.createElement("div"),
h=document.createElement("input"),d=document.createElement("div"),q=document.createElement("div");k.classList.add("nbContainer");c.classList.add("nbSelected");m.classList.add("nbDropdown");h.classList.add("nbSearchInput");d.classList.add("nbList");q.classList.add("nbInputFocuser");h.placeholder=Browser.i18n.getMessage("findANotebook");h.tabIndex=2;q.tabIndex=1;k.appendChild(c);A.appendChild(h);m.appendChild(A);m.appendChild(d);k.appendChild(m);k.appendChild(q);c.addEventListener("click",function(){u()});
h.addEventListener("input",y);h.addEventListener("keydown",function(b){function a(b,c){var d=b[c];d&&d.classList.contains("nbStack")?d="nextElementSibling"===c?d.children[1]:d.lastElementChild:d&&d.parentNode.classList.contains("nbStack")&&d===d.parentNode.children[0]?d=a(d.parentNode,c):!d&&b.parentNode.classList.contains("nbStack")&&(d=a(b.parentNode,c));return d}if(0<=["Up","Down"].indexOf(b.keyIdentifier)){var c="Up"===b.keyIdentifier?"previousElementSibling":"nextElementSibling",e=d.querySelector(".nbHover")||
g;if(e){for(var f=a(e,c);f&&f.classList.contains("nbHidden");)f=a(f,c);f&&!f.classList.contains("nbHidden")&&(e.classList.remove("nbHover"),f.classList.add("nbHover"),f.scrollIntoViewIfNeeded())}b.preventDefault()}});h.addEventListener("keyup",function(b){"Enter"===b.keyIdentifier&&(b=d.querySelector(".nbHover"))&&(t(b),n({userSelected:!0}),u())});q.addEventListener("focus",s);this.addNotebook=function(b){var a=document.createElement("div");a.classList.add("nbNotebook");var c=document.createElement("span");
c.innerText=b.name;for(var e=b.name.split(/\s+/),f=0;f<e.length;f++)p.insert(e[f],a),CommonSelector.SPECIAL_CHAR_REGEX.test(e[f])&&p.insert(e[f].replace(CommonSelector.SPECIAL_CHAR_REGEX,""),a);a.appendChild(c);b.owner&&(c=document.createElement("span"),c.classList.add("nbNotebookOwner"),c.innerText=" ("+b.owner+")",a.appendChild(c));b.type===GlobalUtils.NOTEBOOK_TYPE_LINKED?(a.classList.add("nbLinkedNotebook"),a.setAttribute("globalId",b.globalId),a.setAttribute("shardId",b.shardId)):b.type===GlobalUtils.NOTEBOOK_TYPE_BUSINESS&&
a.classList.add("nbBusinessNotebook");D(a);z(a)||a.classList.add("nbHidden");b.noShareNotes&&a.setAttribute("noShareNotes","");a.addEventListener("click",function(){t(this);n({userSelected:!0});u()});a.addEventListener("mouseover",function(){for(var a=d.querySelectorAll(".nbHover"),b=0;b<a.length;b++)a[b].classList.remove("nbHover");this.classList.add("nbHover")});a.title=a.innerText;a.setAttribute("guid",b.guid);b.visibleToOthers&&a.setAttribute("visibleToOthers","");b.defaultNotebook&&a.setAttribute("default",
"");w(a,b.stack);return a};this.close=x;this.contains=function(b){return k.contains(b)};this.findNotebookByGuid=function(b){for(var a=0;a<d.children.length;a++)if(d.children[a].classList.contains("nbNotebook")){if(d.children[a].getAttribute("guid")===b)return d.children[a]}else if(d.children[a].classList.contains("nbStack"))for(var c=0;c<d.children[a].children.length;c++)if(d.children[a].children[c].getAttribute("guid")===b)return d.children[a].children[c];return null};this.getSelected=function(){var b=
GlobalUtils.NOTEBOOK_TYPE_PERSONAL;c.classList.contains("nbSelectedLinked")?b=GlobalUtils.NOTEBOOK_TYPE_LINKED:c.classList.contains("nbSelectedBusiness")&&(b=GlobalUtils.NOTEBOOK_TYPE_BUSINESS);return{defaultNotebook:c.hasAttribute("default"),globalId:c.getAttribute("globalId"),guid:c.getAttribute("guid"),name:c.innerText,noShareNotes:c.hasAttribute("noShareNotes"),shardId:c.getAttribute("shardId"),type:b}};this.markStatus=function(b){b?c.classList.remove("nbLoading"):c.classList.add("nbLoading")};
this.open=s;this.reset=function(){g=null;p=new Trie;l=[];h.value="";d.innerHTML=""};this.select=t;this.__defineGetter__("height",function(){return m.offsetTop+m.offsetHeight});Object.preventExtensions(this)}Object.preventExtensions(NotebookSelector);
