function TagSelector(d,A,r){function x(b,k){for(var a=0;a<k.length;a++)for(var e=new Tag(k[a].name),f=k[a].name.split(/\s+/),c=0;c<f.length;c++)if(0>e.paths.indexOf(f[c])&&e.paths.push(f[c]),b.insert(f[c],e),CommonSelector.SPECIAL_CHAR_REGEX.test(f[c])){var g=f[c].replace(CommonSelector.SPECIAL_CHAR_REGEX,"");0>e.paths.indexOf(g)&&e.paths.push(g);b.insert(g,e)}}function B(b){if(c.children.length<n&&""!==b&&!p[b.toLowerCase()]){var k=document.createElement("div");k.innerText=b;var a=document.createElement("div");
a.classList.add("tTag");a.title=b;k.classList.add("tTagText");var e=document.createElement("div");e.classList.add("tDeleteTag");e.addEventListener("click",function(){var b=this.parentNode;delete p[b.lastElementChild.innerText.toLowerCase()];b.parentNode.removeChild(b);c.children.length<n&&s();y();r()});a.appendChild(e);a.appendChild(k);c.appendChild(a);c.children.length>=n&&t(l.EXCEEDED_MAX);y();p[b.toLowerCase()]=1}}function m(b){B(b.trim());a.innerHTML="";z(null,"")}function C(b){var a=document.createElement("div");
a.innerText=b;a.title=b;a.classList.add("tDropdownTag");a.addEventListener("mouseover",function(){for(var b=h.querySelectorAll(".tHover"),a=0;a<b.length;a++)b[a].classList.remove("tHover");this.classList.add("tHover")});a.addEventListener("mousedown",function(b){1===b.which&&m(this.innerText);b.preventDefault()});CommonSelector.binaryInsert(h,function(b){return b.innerText},a);u[b]=1}function t(b){a.classList.add("tDisabled");a.contentEditable="false";b===l.EXCEEDED_MAX?a.classList.add("tMax"):b===
l.LINKED_NOTEBOOK&&(a.classList.add("tLinked"),c.style.display="none");r()}function s(){a.classList.remove("tDisabled","tMax","tLinked");a.contentEditable="true";c.style.display="";r()}function y(){for(var b=0,a=c.children.length-1;0<=a;a--)if(b||(b=c.children[a].offsetTop),c.children[a].offsetTop===b)c.children[a].classList.add("lastRow");else if(c.children[a].classList.contains("lastRow"))c.children[a].classList.remove("lastRow");else break}function z(a,k){h.innerHTML="";u={};if(a&&""!==k.trim())for(var c=
k.split(/\s+/),e=a.getMatching(c[0],75),f=0;f<e.length;f++)for(var d=0;d<e[f][1].length;d++){var g;if(g=!p[e[f][1][d].name.toLowerCase()])if(g=!u[e[f][1][d].name])a:{g=c;for(var m=e[f][1][d].paths.join(" "),l=0;l<g.length;l++)if(!RegExp("(\\s|^)"+g[l].replace(/([\\\^\$\.\|\?\*\+\(\)\[\{\]\}])/g,"\\$1"),"i").test(m)){g=!1;break a}g=!0}g&&C(e[f][1][d].name)}A()}var n=20,l={EXCEEDED_MAX:1,LINKED_NOTEBOOK:2},v=new Trie,w=new Trie,q=null,p={},u={};d.classList.add("tContainer");var a=document.createElement("div");
a.classList.add("tInput");a.dataset.placeholder=Browser.i18n.getMessage("quickNote_addTags");a.dataset.maxTagsPlaceholder=Browser.i18n.getMessage("tagNamesNotInRange");a.dataset.linkedPlaceholder=Browser.i18n.getMessage("quickNote_tagsDisabled");a.tabIndex=3;var c=document.createElement("div");c.classList.add("tExisting");var h=document.createElement("div");h.classList.add("tDropdown");s();a.addEventListener("input",function(){a.innerText=a.innerText;a.innerText=a.innerText.replace(/\n/g,"");var b=
a.innerText.split(/\s*,\s*/);if(1<b.length)for(var c=0;c<b.length;c++)m(b[c]);else z(q,a.innerText)});a.addEventListener("blur",function(){m(a.innerText)});a.addEventListener("keydown",function(b){if(13===b.keyCode){var c=h.querySelector(".tHover");c?m(c.innerText):m(a.innerText)}else if(0<=["Up","Down"].indexOf(b.keyIdentifier)){if(c=h.querySelector(".tHover"))var d=null,d="Up"===b.keyIdentifier?c.previousElementSibling:c.nextElementSibling;else d=h.firstElementChild;d&&(d.classList.add("tHover"),
c&&c.classList.remove("tHover"),d.scrollIntoViewIfNeeded());b.preventDefault()}});h.addEventListener("mousedown",function(a){a.preventDefault()});d.appendChild(a);d.appendChild(c);d.appendChild(h);this.abort=function(){var b=document.activeElement===a;a.innerText="";a.blur();return b};this.addBusinessTags=function(a){x(w,a)};this.addPersonalTags=function(a){x(v,a)};this.addTagAndClearInput=m;this.focus=function(){a.focus()};this.getTags=function(){var b=[];if(!a.classList.contains("tDisabled")||!a.classList.contains("tLinked"))for(var d=
0;d<c.children.length;d++)b.push(GlobalUtils.removeControlCharacters(c.children[d].lastElementChild.innerText));return b};this.reset=function(){v=new Trie;w=new Trie;q=null};this.setActiveTrie=function(a){s();c.children.length>=n&&t(l.EXCEEDED_MAX);a===GlobalUtils.NOTEBOOK_TYPE_PERSONAL?q=v:a===GlobalUtils.NOTEBOOK_TYPE_LINKED?t(l.LINKED_NOTEBOOK):a===GlobalUtils.NOTEBOOK_TYPE_BUSINESS&&(q=w)};this.__defineGetter__("height",function(){return h.offsetTop+h.offsetHeight});Object.preventExtensions(this)}
Object.preventExtensions(TagSelector);function Tag(d){this.name=d;this.paths=[];Object.preventExtensions(this)}Object.preventExtensions(Tag);
