function Auth(C,x){function h(){var a={},e;for(e in b){var d=JSON.parse(JSON.stringify(b[e]));a[e]=d}Persistent.set("savedAuthInfo",{userInfo:a,currentUser:c})}function D(){for(var a=0;a<g.length;a++)p(a,{authenticationToken:null,error:"TIMEOUT"});g=[];l=!1}function p(a,c){try{g[a](c)}catch(b){log.warn("Got error running login callback: "+b)}}function y(a){log.warn("failed login: "+a.trace);a=E(a);for(var c=0;c<g.length;c++)p(c,{error:a});g=[];l=!1}function q(a,e){if(l)if(t&&clearTimeout(t),a)if(a.secondFactorRequired){for(var d=
0;d<g.length;d++)p(d,{authenticationToken:a.authenticationToken,secondFactorDeliveryHint:a.secondFactorDeliveryHint,expiration:(new Date).getTime()-a.currentTime+a.expiration});g=[];l=!1}else{if(a.user&&a.user.id)if(s=(new Date).getTime()-a.currentTime,c=a.user.id.toString(),b[c]={},b[c].username=a.user.username,b[c].authenticationToken=a.authenticationToken,b[c].expiration=a.expiration,b[c].premium=a.user.premiumInfo?a.user.premiumInfo.premium:!1,b[c].shardId=a.user.shardId,b[c].fullName=a.user.name||
a.user.username,b[c].email=a.user.email,b[c].quota=a.user.accounting.uploadLimit,b[c].monthEnd=a.user.accounting.uploadLimitEnd,a.user.businessUserInfo)b[c].businessId=a.user.businessUserInfo.businessId,b[c].bizName=a.user.businessUserInfo.businessName,h(),m().client.UserStore.authenticateToBusiness(z,a.authenticationToken);else{h();n.showLoggedInState();for(d=0;d<g.length;d++)p(d,{authenticationToken:a.authenticationToken,username:a.user.username,userId:c,error:!1,premium:a.user.premiumInfo?a.user.premiumInfo.premium:
!1,fullName:a.user.name||a.user.username});g=[];l=!1}}else y(e)}function z(a,e){if(a){b[c]?(b[c].bizAuthenticationToken=a.authenticationToken,b[c].bizExpiration=a.expiration):log.warn("Got business login for unknown user. Discarding.");h();n.showLoggedInState();for(var d=0;d<g.length;d++)p(d,{authenticationToken:b[c].authenticationToken,bizAuthenticationToken:a.authenticationToken,username:b[c].username,userId:c,error:!1,premium:b[c].premium,fullName:b[c].fullName});g=[];l=!1}else if(/BUSINESS_SECURITY_LOGIN_REQUIRED/.test(e.trace)){delete b[c].bizAuthenticationToken;
delete b[c].bizExpiration;h();n.showLoggedInState();for(d=0;d<g.length;d++)p(d,{sso:!0,bizName:b[c].bizName,username:b[c].username});g=[];l=!1}else y(e)}function E(a){if(!a)return"UNKNOWN";if("number"===typeof a.code)switch(a.code){case 0:return"NETWORK";case 503:return"HTTP/503"}for(var c=["name","trace"],b=0;b<c.length;b++)if(a[c[b]]){var k=a[c[b]],f=k.match(/errorCode:(\w+)/);if(f)switch(f[1]){case "DATA_REQUIRED":return k.match(/parameter:password/)?"PASSWORD_REQUIRED":k.match(/parameter:username/)?
"USERNAME_REQUIRED":"DATA_REQUIRED";case "INVALID_AUTH":return k.match(/parameter:password/)?"INVALID_PASSWORD":k.match(/parameter:username/)?"INVALID_USERNAME":k.match(/parameter:oneTimeCode/)?"INVALID_TWO_STEP_CODE":"INVALID_AUTH";case "PERMISSION_DENIED":return k.match(/parameter:.*tooManyFailures/)||k.match(/parameter:.*tooManyMessageAttempts/)?"TOO_MANY_FAILURES":k.match(/parameter:.*User.active/)?"ACCOUNT_DEACTIVATED":k.match(/parameter:authenticationToken/)?"EXPIRED_AUTHENTICATION_TOKEN":"PERMISSION_DENIED";
case "AUTH_EXPIRED":return k.match(/parameter:password/)?"EXPIRED_PASSWORD":k.match(/parameter:authenticationToken/)?"EXPIRED_AUTHENTICATION_TOKEN":"AUTH_EXPIRED";case "BAD_DATA_FORMAT":return k.match(/parameter:username/)?"INVALID_USERNAME":"INVALID_AUTH";default:return log.warn("Found unhandled error condition: "+f[1]+k+" while logging in."),"UNKNOWN"}}log.warn("nothing");return"UNKNOWN"}function u(a){for(;c;)A(a)}function A(a){a||m().client.UserStore.revokeLongSession(function(a,c){c&&log.error("problem revoking auth token: "+
c.trace)},b[c].authenticationToken);delete b[c];c="";for(var e in b){c=e;break}h();s=0;0==Object.keys(b).length&&n.showLoggedOutState()}function B(a){var e=v();if(e.authenticationToken){var d={authenticationToken:e.authenticationToken};e.bizAuthenticationToken?new Date+18E4>e.bizExpiration?m().client.UserStore.authenticateToBusiness(function(e,f){e?(b[c].bizAuthenticationToken=e.authenticationToken,b[c].bizExpiration=e.expiration,h(),d.bizAuthenticationToken=e.authenticationToken,a(d)):f.trace?/PERMISSION_DENIED/.test(f.trace)&&
(/parameter:Business/.test(f.trace)||/parameter:Business\.status/.test(f.trace))?(delete b[c].bizAuthenticationToken,delete b[c].bizExpiration,delete b[c].businessId,delete b[c].bizName,h(),a(d)):/BUSINESS_SECURITY_LOGIN_REQUIRED/.test(f.trace)?(delete b[c].bizAuthenticationToken,delete b[c].bizExpiration,h(),a(d)):(log.error("problem refreshing business token: "+f.trace),u(),a(null)):(log.warn("network was down when trying to refresh biz auth token, but still called callback"),a(d))},e.authenticationToken):
(d.bizAuthenticationToken=e.bizAuthenticationToken,a(d)):a(d)}else a(null)}function m(){var a;a=x+n.getBootstrapInfo("serviceHost")+"/json";if(w[a])a=w[a];else{var c=new JsonRpc(null,["UserStore.authenticateLongSession","UserStore.authenticateToBusiness","UserStore.revokeLongSession","UserStore.completeTwoFactorAuthentication","UserStore.getUser"],null,x,n.getBootstrapInfo("serviceHost"),C);c.initWithUrl(a);a=w[a]=c}return a}function v(a){a||(a=c);return(a=b[a])?a:{}}function r(a){if(/macintosh/i.test(a))a=
"MacOS";else if(/windows/i.test(a))if(a=a.match(/Windows NT (.+);/))switch(a[1]){case "3.1":a="Windows NT 3.1";break;case "3.5":a="Windows NT 3.5";break;case "3.51":a="Windows NT 3.51";break;case "4.0":a="Windows NT 4.0";break;case "5.0":a="Windows 2000";break;case "5.01":a="Windows 2000 SP1";break;case "5.1":a="Windows XP";break;case "5.2":a="Windows XP x64";break;case "6.0":a="Windows Vista";break;case "6.1":a="Windows 7";break;case "6.2":a="Windows 8";break;case "6.3":a="Windows 8.1";break;default:a=
"Windows"}else a="Windows";else a=/linux/i.test(a)?"Linux":"Unknown Operating System";return SAFARI?"Safari ("+a+")":OPERA?"Opera ("+a+")":YANDEX?"Yandex ("+a+")":"Google Chrome ("+a+")"}var n=Browser.extension.getBackgroundPage().extension;n.getBootstrapInfo("serviceHost");var w={},b={},c=null,s=0,g=[],t=0,l=!1;(function(){var a=Persistent.get("savedAuthInfo");b={};c="";if(a&&a.currentUser&&a.userInfo){c=a.currentUser;for(var e in a.userInfo)try{b[e]=a.userInfo[e]}catch(d){log.warn("Couldn't restore credentials for user "+
e)}if(!b[c])for(e in log.warn("No entry for saved user, picking another."),b){currentuser=e;h();break}}else Persistent.set("savedAuthInfo",{})})();this.getAuthTokens=B;this.isAuthenticated=function(a){function e(e,f){e?(b[c].bizAuthenticationToken=e.authenticationToken,b[c].bizExpiration=e.expiration,h(),d.bizAuthenticationToken=e.authenticationToken,d.bizExpiration=e.expiration,a(d)):f&&f.trace?/PERMISSION_DENIED/.test(f.trace)&&(/parameter:Business/.test(f.trace)||/parameter:Business\.status/.test(f.trace))?
(delete d.businessId,delete b[c].businessId,delete b[c].bizAuthenticationToken,delete b[c].bizExpiration,delete b[c].bizName,h(),a(d)):/BUSINESS_SECURITY_LOGIN_REQUIRED/.test(f.trace)?(delete b[c].bizAuthenticationToken,delete b[c].bizExpiration,h(),a(d)):(log.error("problem refreshing business auth token: "+f.trace),u(),a(null)):(log.warn("network was down when trying to refresh biz auth token, but still called callback"),a(d))}var d={};(new Bootstrapper(options.get("simulateSimplifiedChinese"),
options.get("useStage"),options.get("overrideServiceURL"),options.get("secureProto"))).bootstrap(function(b){if(b){b=v();var f;if(f=b.authenticationToken)b.expiration?(f=(new Date).getTime(),f-=s,f=f>b.expiration-18E4?!1:!0):f=!1;f?(d={username:b.username,authenticationToken:b.authenticationToken,userId:c,shardId:b.shardId,premium:b.premium,fullName:b.fullName,email:b.email},b.businessId?(d.businessId=b.businessId,b.bizExpiration&&b.bizAuthenticationToken?(f=(new Date).getTime(),f-=s,f=f>b.bizExpiration-
18E4?!1:!0):f=!1,f?(d.bizAuthenticationToken=b.bizAuthenticationToken,d.bizExpiration=b.bizExpiration,a(d)):m().client.UserStore.authenticateToBusiness(e,b.authenticationToken)):a(d)):a(null)}else log.warn("Version out of date!")},!1)};this.login=function(a,b,c){c&&g.push(c);l||(l=!0,SAFARI?m().client.UserStore.authenticateLongSession(q,a,b,"en-safari-clipper-xauth-new","1fbffc8cf53bd605",Persistent.get("deviceID"),r(navigator.userAgent),!0):OPERA?m().client.UserStore.authenticateLongSession(q,a,
b,"en-opera-clipper-xauth-new","bda9ae45efd276dc",Persistent.get("deviceID"),r(navigator.userAgent),!0):YANDEX?m().client.UserStore.authenticateLongSession(q,a,b,"en-yandex-clipper-xauth-new","6281f15aacf2b24a",Persistent.get("deviceID"),r(navigator.userAgent),!0):m().client.UserStore.authenticateLongSession(q,a,b,"en-chrome-clipper-xauth-new","57542b7c39ab82e9",Persistent.get("deviceID"),r(navigator.userAgent),!0),t=setTimeout(D,3E4))};this.logout=A;this.logoutAll=u;this.getCurrentUser=function(){return c};
this.getUserInfo=v;this.completeTwoFactorAuthentication=function(a,b,c){c&&g.push(c);l||(l=!0,m().client.UserStore.completeTwoFactorAuthentication(q,a,b,Persistent.get("deviceID"),r(navigator.userAgent)))};this.updateUserStatus=function(){B(function(a){a?m().client.UserStore.getUser(function(a,d){a?(c=a.id.toString(),b[c]&&(b[c].username=a.username,b[c].premium=a.premiumInfo?a.premiumInfo.premium:!1,b[c].shardId=a.shardId,b[c].fullName=a.name||a.username,b[c].email=a.email,b[c].quota=a.accounting.uploadLimit,
b[c].monthEnd=a.accounting.uploadLimitEnd,a.businessUserInfo?(b[c].businessId=a.businessUserInfo.businessId,b[c].bizName=a.businessUserInfo.businessName,h(),m().client.UserStore.authenticateToBusiness(z,b[c].authenticationToken)):(delete b[c].businessId,delete b[c].bizAuthenticationToken,delete b[c].bizExpiration,delete b[c].bizName,h()))):log.error("error when updating user status: "+d.__proto__.name+JSON.stringify(d))},a.authenticationToken):log.error("no tokens found when trying to update user status")})};
Object.preventExtensions(this)}Object.preventExtensions(Auth);
