function ClipResultBackground(){function l(a,b,c){c=document.getElementById("copier");c.value=a.text;c.select();Browser.sendToTab(b.tab,{name:"sh_urlCopied",copied:document.execCommand("copy",!1,null)})}function k(a,b,c){function d(a){Browser.sendToTab(b.tab,{name:"cr_receiveRelatedNotes",relatedNotes:a})}(c=extension.getPendingNote(a.pendingNoteKey))&&c.relatedNotes?(a=null,auth.getUserInfo().bizAuthenticationToken&&(a=/S=([^:]+)/.exec(auth.getUserInfo().bizAuthenticationToken)[1]),d(extension.combineRelatedNotes(c.relatedNotes.pers,
auth.getUserInfo().shardId,c.relatedNotes.biz,a,c.relatedNotes.containingNotebooks))):a.recText?sidebarBackground.getSmartFilingInfo({notesOnly:!0,pendingNoteKey:a.pendingNoteKey,recText:a.recText,callback:function(a,b){k({pendingNoteKey:a},b)}},b):d([])}Browser.addMessageHandlers({copyText:l,emailNote:function(a,b,c){function d(a,b){b&&log.error(b)}var f;f=new JsonRpc(null,["NoteStore.emailNote","NoteStoreExtra.emailNotesSharedWorkaround"],null,options.get("secureProto"),extension.getBootstrapInfo("serviceHost"),
options.get("overrideServiceURL"));f.initWithAuthToken(a.token,function(){a.shared?f.client.NoteStoreExtra.emailNotesSharedWorkaround(d,a.token,auth.getUserInfo().authenticationToken,{javaClass:"java.util.ArrayList",list:a.recipients},{javaClass:"java.util.ArrayList",list:[a.noteGuid]},a.message):f.client.NoteStore.emailNote(d,a.token,{guid:a.noteGuid,toAddresses:{javaClass:"java.util.ArrayList",list:a.recipients},message:a.message})})},findContacts:function(a,b,c){function d(a){Browser.sendToTab(b.tab,
{name:"sh_receiveContacts",contacts:a})}function f(a){log.error(a)}auth.isAuthenticated(function(b){b?extension.createNoteStoreClient(b.shardId).findContacts(b.authenticationToken,new ContactsQuery({maxEntries:5,prefix:a.prefix}),d,f):log.error("not logged in while finding contacts")})},getRelatedNotes:k,getSameSiteNotes:function(a,b,c){function d(a,c){a.name="cr_receiveSameSiteNotes";Browser.sendToTab(b.tab,a)}function f(a){g=a;(e.bizAuthenticationToken&&h||!e.bizAuthenticationToken)&&d(k())}function l(a){h=
a;g&&d(k())}function k(){for(var a=0;a<g.notes.list.length;a++)g.notes.list[a].shardId=m.shardId;if(e.bizAuthenticationToken){for(a=0;a<h.notes.list.length;a++)h.notes.list[a].shardId=n.shardId,h.notes.list[a].inBusinessNotebook=!0,g.notes.list.push(h.notes.list[a]);g.notes.list.sort(function(a,b){return b.updated-a.updated})}return g}function p(){m.client.NoteStoreExtra.findNotesWithSnippet(f,e.authenticationToken,q,0,r,s);e.bizAuthenticationToken&&n.client.NoteStoreExtra.findNotesWithSnippet(l,
e.bizAuthenticationToken,q,0,r,s)}var s=a.resultSpec,q=a.noteFilter,e,m,n,g,h,r=10;auth.isAuthenticated(function(a){if((e=a)&&e.authenticationToken){var b=options.get("secureProto")+extension.getBootstrapInfo("serviceHost");m=new JsonRpc(null,["NoteStoreExtra.findNotesWithSnippet"],b,options.get("secureProto"),extension.getBootstrapInfo("serviceHost"),options.get("overrideServiceURL"));m.initWithAuthToken(e.authenticationToken,function(){e.bizAuthenticationToken?(n=new JsonRpc(null,["NoteStoreExtra.findNotesWithSnippet"],
b,options.get("secureProto"),extension.getBootstrapInfo("serviceHost"),options.get("overrideServiceURL")),n.initWithAuthToken(e.bizAuthenticationToken,p)):p()})}else d(null)});c&&c()},initializeClipResult:function(a,b,c){a.name="cr_initialize";a.baseUrl=options.get("secureProto")+extension.getBootstrapInfo("serviceHost");a.locale=extension.getBootstrapInfo("name");a.userId=auth.getCurrentUser();a.afterClip=options.get("afterClip");a.premium=auth.getUserInfo().premium;Browser.sendToTab(b.tab,a)},setReminder:function(a,
b,c){b=new NoteAttributes({source:"web.clip",sourceURL:a.sourceURL,reminderOrder:a.reminderOrder});a.reminderTime&&(b.reminderTime=a.reminderTime);extension.createNoteStoreClient(a.shardId).updateNote(a.token,new Note({guid:a.noteGuid,title:a.title,attributes:b}),function(){},function(a){log.error(a)})},shareNote:function(a,b,c){var d=null,d=/S=(s\d+):/.exec(a.token)[1];extension.createNoteStoreClient(d).shareNote(a.token,a.guid,function(c){c=options.get("secureProto")+extension.getBootstrapInfo("serviceHost")+
"/shard/"+d+"/sh/"+a.guid+"/"+c;Browser.sendToTab(b.tab,{name:"sh_complete",url:c});"url"===a.shareType&&l({text:c},b)},function(a){log.error(a)})}});Object.preventExtensions(this)}Object.preventExtensions(ClipResultBackground);new ClipResultBackground;
