function SidebarBackground(){function w(c,l,w){function p(){var b={},f=extension.getPendingNote(c.pendingNoteKey);f||(f={});f.relatedNotes||(f.relatedNotes={});f.relatedNotes.pers=e&&e.relatedNotes?e.relatedNotes.list:[];g&&(f.relatedNotes.biz=g.relatedNotes?g.relatedNotes.list:[],f.relatedNotes.containingNotebooks=x);extension.setPendingNote(c.pendingNoteKey,f);c.notesOnly?c.callback(c.pendingNoteKey,l):("smartFiling"===options.get("notebookSelection")&&(e&&e.notebook&&(b.notebook=e.notebook),m&&
options.get("bizSmartFilingEnabled")&&g&&g.notebook&&!g.notebook.restrictions.noCreateNotes&&(b.notebook=g.notebook,b.notebook.biz=!0)),options.get("smartFilingTags")&&(e&&e.tags&&(b.tags=e.tags),m&&g&&g.tags&&b.notebook&&b.notebook.biz&&(b.tags=g.tags)),b.name="receiveSmartFilingInfo",Browser.sendToTab(l.tab,b))}function z(){r=new JsonRpc(null,["NoteStoreExtra.getFilingRecommendations"],null,options.get("secureProto"),extension.getBootstrapInfo("serviceHost"),options.get("overrideServiceURL"));r.initWithAuthToken(t,
function(){m?(n=new JsonRpc(null,["NoteStoreExtra.getFilingRecommendations"],null,options.get("secureProto"),extension.getBootstrapInfo("serviceHost"),options.get("overrideServiceURL")),n.initWithAuthToken(m,function(){s()})):s()})}function s(){var b={relatedNotesResultSpec:{includeAttributes:!0,includeNotebookGuid:!0,includeTitle:!0,includeUpdated:!0},text:c.recText,url:l.tab.url};options.get("includeDebugInfo")&&(b.relatedNotesResultSpec.includeDebugInfo=!0);var f=options.get("relatedNotesContext").trim();
""!=f&&(b.context=f);JsonQueue.handleExpensiveOpRequest({shardId:r.shardId,userId:u,type:"pers"},r.client.NoteStoreExtra.getFilingRecommendations,C,t,b);m&&JsonQueue.handleExpensiveOpRequest({shardId:n.shardId,userId:u,type:"biz"},n.client.NoteStoreExtra.getFilingRecommendations,D,m,b)}function D(b,f){v=!0;if(b){if(b.relatedNotes){x={};for(var c=0;c<b.containingNotebooks.list.length;c++){var e=b.containingNotebooks.list[c];x[e.guid]={joined:e.hasSharedNotebook,name:e.notebookDisplayName,contact:e.contactName}}}b.debugInfo&&
(q.write("DEBUG_INFO",b.debugInfo),delete b.debugInfo);g=b}else resolveError(f,l.tab);h&&p()}function C(b,f){h=!0;b?(e=b,b.debugInfo&&(q.write("TEXT",c.recText),q.write("DEBUG_INFO",b.debugInfo),delete b.debugInfo)):resolveError(f,l.tab);(m&&v||!m)&&p()}var x,e,g,r,n,h,v,t=auth.getUserInfo().authenticationToken,m=auth.getUserInfo().bizAuthenticationToken,u=auth.getCurrentUser(),q=new LogWriter("relatedNotesDebugInfo");c.recText&&c.recText.trim()?z():p()}Browser.addMessageHandlers({getNotebooks:function(c,
l,w){function p(a){Browser.sendToTab(l.tab,{name:(c.page?c.page+"_":"")+"receivePersonalNotebooks",alwaysStartInNotebookGuid:m,notebooks:a,recentNotebookGuid:t})}function z(a){for(var f in a.linkedNotebooks){var d=a.linkedNotebooks[f];d.sharedNotebookGlobalId&&d.shardId&&(y[d.sharedNotebookGlobalId]=d,u&&d.businessId===u||(q[d.shardId]||(q[d.shardId]=extension.createNoteStoreClient(d.shardId)),b++,q[d.shardId].authenticateToSharedNotebook(d.sharedNotebookGlobalId,h.authenticationToken,D,g)))}a.updateCount===
a.chunkHighUSN?(H=!0,n(),J=!0,r()):A.getFilteredSyncChunk(h.authenticationToken,a.chunkHighUSN,B,K,z,e)}function s(a){a.notebooks&&0<a.notebooks.length&&(k=k.concat(a.notebooks));a.updateCount===a.chunkHighUSN?(L=!0,r()):E.getFilteredSyncChunk(h.bizAuthenticationToken,a.chunkHighUSN,B,F,s,e)}function D(a){var b=null,d=null,e=null;a.user?(b=a.user.id,d=a.user.name||a.user.username,e=a.user.shardId):a.publicUserInfo&&(b=a.publicUserInfo.userId,d=a.publicUserInfo.username,e=a.publicUserInfo.shardId);
y[a.input_args[0]].ownerId=b;y[a.input_args[0]].ownerName=d;a.authenticationToken&&e?q[e].getFilteredSyncChunk(a.authenticationToken,0,1,F,C,g):(f++,n())}function C(a){f++;for(var b in a.notebooks){var d=a.notebooks[b];if(!d.restrictions.noCreateNotes)for(var e in d.sharedNotebooks){var c=y[d.sharedNotebooks[e].globalId];if(c){d={globalId:c.sharedNotebookGlobalId,guid:d.guid,name:c.shareName,noShareNotes:d.restrictions.noShareNotes,shardId:c.shardId,stack:c.stack,type:GlobalUtils.NOTEBOOK_TYPE_LINKED,
visibleToOthers:!0};c.ownerId!==v&&(d.owner=c.ownerName);G.push(d);break}}}n()}function x(a){log.error(a)}function e(a){log.error(a)}function g(a){f++;n();log.error(a)}function r(){if(L&&J){for(var a in k)if(!k[a].restrictions.noCreateNotes)for(var b in k[a].sharedNotebooks){var d=y[k[a].sharedNotebooks[b].globalId];if(d){d={globalId:d.sharedNotebookGlobalId,guid:k[a].guid,name:d.shareName,noShareNotes:k[a].restrictions.noShareNotes,shardId:d.shardId,stack:d.stack,type:GlobalUtils.NOTEBOOK_TYPE_BUSINESS,
visibleToOthers:1<(k[a].sharedNotebooks?k[a].sharedNotebooks.length:0)||k[a].published};k[a].contact.id!==v&&(d.owner=k[a].contact.name||k[a].contact.username);G.push(d);break}}I=!0;n()}}function n(){!H||f!==b||h.bizAuthenticationToken&&!I||Browser.sendToTab(l.tab,{name:(c.page?c.page+"_":"")+"receiveSharedNotebooks",alwaysStartInNotebookGuid:m,notebooks:G,recentNotebookGuid:t})}var h=auth.getUserInfo(),v=parseInt(auth.getCurrentUser()),t=null,m=null,u=null,q={},b=0,f=0,H=!1,I=!1,G=[],y={},k=[],J=
!1,L=!1,A,E,B=50,F=new SyncChunkFilter({includeNotebooks:!0}),K=new SyncChunkFilter({includeLinkedNotebooks:!0});(function(){var a=Persistent.get("recentNotebooks");a||(a={});t=a[v+""];"alwaysStartIn"===options.get("notebookSelection")&&(m=options.get("startNotebook"));u=h.businessId;A=extension.createNoteStoreClient(h.shardId);A.listNotebooks(h.authenticationToken,p,x);A.getFilteredSyncChunk(h.authenticationToken,0,B,K,z,e);h.bizAuthenticationToken&&(E=extension.createNoteStoreClient(/S=([^:]+)/.exec(h.bizAuthenticationToken)[1]),
E.getFilteredSyncChunk(h.bizAuthenticationToken,0,B,F,s,e))})()},getSmartFilingInfo:w,getTags:function(c,l,w){function p(c){console.log(c)}extension.getOption("alwaysTagWith")&&Browser.sendToTab(l.tab,{name:"receiveAlwaysTags",tags:extension.getOption("alwaysTags").split(/\s*,\s*/)});(function(){var c=auth.getUserInfo();extension.createNoteStoreClient(c.shardId).listTags(c.authenticationToken,function(c){Browser.sendToTab(l.tab,{name:"receivePersonalTags",tags:c})},p);if(c.bizAuthenticationToken){var s=
/^S=([^:]+)/.exec(c.bizAuthenticationToken)[1];extension.createNoteStoreClient(s).listTags(c.bizAuthenticationToken,function(c){Browser.sendToTab(l.tab,{name:"receiveBusinessTags",tags:c})},p)}})()}});this.getSmartFilingInfo=w;Object.preventExtensions(this)}Object.preventExtensions(SidebarBackground);var sidebarBackground=new SidebarBackground;
