function Submitter(t,u,G,K,p){function v(a){var e;switch(a.name){case "EDAMNotFoundException":"Note.notebookGuid"==a.identifier&&(e="unknownNotebook");break;case "EDAMUserException":switch(a.errorCode){case EDAMErrorCode.BAD_DATA_FORMAT:switch(a.parameter){case "Note.content":e="noteSizeExceeded"}break;case EDAMErrorCode.LIMIT_REACHED:switch(a.parameter){case "Note":e="overQuota";break;case "Note.size":e="noteSizeExceeded";break;case "Note.resources":e="noteSizeExceeded";break;case "Resource.data.size":e=
"noteSizeExceeded"}break;case EDAMErrorCode.QUOTA_REACHED:"Accounting.uploadLimit"==a.parameter&&(e="overQuota")}}e||log.error(b.attributes.sourceURL+a.__proto__.name+JSON.stringify(a));"noteSizeExceeded"===e?extension.trackEvent({category:"Errors",action:"Too big"+(u?"-premium":"-free"),label:b.attributes.sourceURL}):"overQuota"===e?extension.trackEvent({category:"Errors",action:"Over quota",label:b.attributes.sourceURL}):extension.trackEvent({category:"Errors",action:"Thrift: "+JSON.stringify(a).substr(0,
200),label:b.attributes.sourceURL});p({name:"fail",error:e,tokens:t})}function H(a){console.log(a);(function(){var b={name:"success",noteSize:m,noteGuid:a.guid,shardId:/^"?S=([^:]+)/.exec(n)[1],notebookName:x,noShareNotes:y,skitchNote:z,tokens:t};!b.notebookName||!0!==b.noShareNotes&&!1!==b.noShareNotes?w.getNotebook(n,a.notebookGuid,function(a){b.notebookName=a.name;b.noShareNotes=a.restrictions.noShareNotes;p(b)},function(a){log.error(a.name+" "+JSON.stringify(a));p(b)}):p(b)})()}function I(a){if(255===
a[0]&&216===a[1]&&255===a[2])return EDAM_MIME_TYPE_JPEG;if(137===a[0]&&80===a[1]&&78===a[2]&&71===a[3]&&13===a[4]&&10===a[5]&&26===a[6]&&10===a[7]||0===a[0]&&0===a[1]&&1===a[2]&&0===a[3])return EDAM_MIME_TYPE_PNG;if(71!==a[0]||73!==a[1]||70!==a[2]||56!==a[3]||55!==a[4]&&57!==a[4]||97!==a[5]){if(37===a[0]&&80===a[1]&&68===a[2]&&70===a[3])return EDAM_MIME_TYPE_PDF;if(82===a[0]&&73===a[1]&&70===a[2]&&70===a[3]&&87===a[8]&&69===a[9]&&66===a[10]&&80===a[11])return"image/webp"}else return EDAM_MIME_TYPE_GIF;
return EDAM_MIME_TYPE_DEFAULT}function J(a,b,m,r,h){a=GlobalUtils.unescapeXML(a);var f=new XMLHttpRequest;f.open("GET",a);f.responseType="arraybuffer";f.url=a;f.original=m;f.loc=b;f.index=h;B++;f.onreadystatechange=function(){4===this.readyState&&(200===this.status&&this.response&&0<this.response.byteLength?(g[this.index]={byteArray:new Uint8Array(this.response),loc:this.loc,orig:this.original,url:this.url},"evernote_attachment_url"===r&&(g[this.index].attachment=!0,g[this.index].fileName=/evernote_attachment_name="([^"]*)"/.exec(m)[1])):
g[this.index]={loc:this.loc,orig:this.original},C++,D())};try{f.send()}catch(k){}}function D(){if(E&&B===C){for(var a=g.length-1;0<=a;a--)if(g[a])if(g[a].byteArray){var e=g[a].byteArray,A=g[a].loc,r=g[a].orig,h=g[a].url,f=g[a].fileName,k=g[a].attachment;b.resources||(b.resources=[]);var l=I(e),d,q=e.buffer;d=l;var c=new Resource;c.data=new Data;c.data.body=q;c.mime=d;c.attributes=new ResourceAttributes;c.attributes.sourceURL=GlobalUtils.removeControlCharacters(h);c.attributes.fileName=f;if(!f&&h&&
(q=/.+\/(.+?)(?:$|\?)/.exec(h)))try{c.attributes.fileName=decodeURIComponent(q[1])}catch(s){if("URI malformed"==s.message)c.attributes.fileName=unescape(q[1]);else throw s;}c.attributes.fileName&&!(d===EDAM_MIME_TYPE_JPEG?/\.jpe?g$/.test(c.attributes.fileName):d===EDAM_MIME_TYPE_PNG?/\.png$/.test(c.attributes.fileName):d===EDAM_MIME_TYPE_GIF?/\.gif$/.test(c.attributes.fileName):d===EDAM_MIME_TYPE_PDF?/\.pdf$/.test(c.attributes.fileName):"image/webp"===d?/\.webp$/.test(c.attributes.fileName):1)&&(c.attributes.fileName+=
d===EDAM_MIME_TYPE_JPEG?".jpg":d===EDAM_MIME_TYPE_PNG?".png":d===EDAM_MIME_TYPE_GIF?".gif":d===EDAM_MIME_TYPE_PDF?".pdf":"image/webp"===d?".webp":"");c.attributes.fileName&&(c.attributes.fileName=GlobalUtils.removeControlCharacters(c.attributes.fileName));c.attributes.attachment=!!k;d=c;b.resources.push(d);m+=d.data.body.byteLength;d=b;q=b.content.slice(0,A);k=l;l=r;h='<en-media type="';e=SparkMD5.ArrayBuffer.hash(e.buffer);h+=k+'" hash="'+e+'"';e=/(?:\s|")(style|title|lang|xml:lang|dir|height|width|usemap|align|border|hspace|vspace|longdesc|alt)\s*=\s*"([^"]+)"/ig;
k=e.exec(l);for(f=l.indexOf(">");k&&k.index<f;)""!=k[2].trim()&&(h+=" "+k[1]+'="'+k[2]+'"'),k=e.exec(l);h+="></en-media>";d.content=q+h+b.content.slice(A+r.length)}else/(evernote_attachment|^<embed)/.test(g[a].orig)&&(b.content=b.content.slice(0,g[a].loc)+b.content.slice(g[a].loc+g[a].orig.length));b.content=GlobalUtils.removeControlCharacters(b.content);b.content.length>EDAM_NOTE_CONTENT_LEN_MAX?(a=new EDAMUserException,a.errorCode=EDAMErrorCode.BAD_DATA_FORMAT,a.parameter="Note.content",v(a)):(m+=
b.content.length,u&&209715200<m||!u&&m>EDAM_NOTE_SIZE_MAX_FREE?(a=new EDAMUserException,a.errorCode=EDAMErrorCode.LIMIT_REACHED,a.parameter="Note.size",v(a)):(p({name:"showSyncing"}),w.createNote(n,b,H,v)))}}var w,F,m=0,E=!1,B=0,C=0,g=[],b=new Note,z=!1,n=t.submit,x,y;this.createNoteWithThrift=function(a,e,m,r,h,f,k,l,d,q){b.attributes=new NoteAttributes;"clearly"===l?b.attributes.source="Clearly":(b.attributes.source="web.clip","screenshot"===l&&(z=!0));b.attributes.sourceURL=GlobalUtils.removeControlCharacters(k);
b.content='<?xml version="1.0" encoding="utf-8"?><!DOCTYPE en-note SYSTEM "http://xml.evernote.com/pub/enml2.dtd"><en-note>';f&&f.trim()&&(b.content+=GlobalUtils.escapeXML(f)+"<hr/>");b.content+="<br/>"+d+"<br/></en-note>";f=/<(?:img|embed|div) [^>]*?(src|evernote_attachment_url)="(data:[^>,]+,)?(resource:)?([^">]+)"[^>]*>.*?<\/(?:img|embed|div)>/g;var c=f.exec(b.content);for(k=0;c;){if(c[2]){l=c.index;d=c[0];for(var s=k++,c=decodeURIComponent(c[4]).split("&")[0],c=window.atob(c),p=new Uint8Array(2*
c.length),n=0;n<c.length;n++)p[n]=c.charCodeAt(n);g[s]={byteArray:p,loc:l,orig:d}}else c[3]?(l=q[parseInt(c[4])],d=c.index,s=c[0],c=k++,l.bytes.length=l.byteLength,g[c]={byteArray:new Uint8Array(l.bytes),loc:d,orig:s,url:b.attributes.sourceURL}):J(c[4],c.index,c[0],c[1],k++);c=f.exec(b.content)}b.title=a;b.notebookGuid=e;x=m;y=r;h&&0<h.length&&(b.tagNames=h);E=!0;D()};Object.preventExtensions(this);(function(){F=/^"?S=(s\d+)/.exec(n)[1];var a=new Thrift.BinaryHttpTransport(G+"/edam/note/"+F),a=new Thrift.BinaryProtocol(a);
w=new NoteStoreClient(a)})()}Object.preventExtensions(Submitter);
