#!/bin/sh

# bkup <filename>
# if <filename> exists, it is moved to a file with name <filename>.N~
# for N greater than whatever exists already.

PATH=/usr/bin:/usr/ucb:/bin

if [ $# -ne 1 ]; then
    echo 1>&2 $0: needs exactly one argument, a filename
    exit 1
fi

if [ ! -f $1 ]; then
    exit 0
fi

highest=`
    ls -r $1* |
    sed -n -e '/.*\.~\([0-9][0-9]*\)~/{s//\1/p;
                                        q
                                      }'
`
if [ "$highest" ]; then
    next=`expr $highest + 1`
else
    next=1
fi

cp -p $1 $1.~${next}~

#end bkup
