#!/bin/sh

# cfuncs is a filter
# it prints out the names of the functions defined in the given file,
# assuming that function names are the only identifiers that start left
# aligned in a line that contains a left parenthesis.

/bin/sed -n -e 's/^\([a-zA-Z_][a-zA-Z_]*\)(.*/\1/p' $*

# end of cfuncs
