#!/bin/sh

PATH=/usr/bin:/bin

default=',* #* *~ .*~ *.BAK .*.BAK core a.out *.stackdump'

case $# in
0)  ;;
1)  cd $1;;
*)  echo 1>&2 usage: `basename $0` '[directory]'
    exit 1;;
esac

rm -f ${TRASH-${default}}
