#!/bin/sh

PATH=/usr/local/bin:/bin:/usr/bin
export PATH

# counts files and revisions downwards from a given module directory
# in the repository (NOT in the sandboxes).

case $# in 
0)	echo "usage: $0 moduledir..."
	echo "	cd to the repository before applying,"
	echo "	and call this only on real modules."
	exit 2
	;;
esac

find "$@" -type f -name '*,v' -exec rlog {} \; |
sed -n 's/^total revisions: \([0-9][0-9]*\);.*/\1/p' |
awk '{ sum += $1 } END { print "files="NR, "revisions="sum; }'

#end cvscount
