#!/bin/sh

# inspired by /usr/share/xemacs*/etc/editclient.sh
# updated for Emacs 23
# rewritten for Emacs 24
# massively simplified when I gave up on the xemacs one.
# rewritten once more

OPATH=$PATH
PATH=/usr/bin:/bin

emacs=/usr/local/bin/emacs
emacsclient=/usr/local/bin/emacsclient
emacsserver="$emacs -geometry -0+0 -f server-start"
server_is_up () { $emacsclient -e t 1>/dev/null 2>&1; }
progname=$(basename $0);

case $# in
0)
    progname="$(basename $0)"
    echo "usage: $(basename $0) emacsclient-args"
    echo "	runs $emacsclient, but first makes sure a server is present."
    echo
    echo "	$progname -n ...	does not wait in the foreground"
    echo "	$progname -c ...	starts a new frame"
    exit 1 ;;
esac

server_is_up || (
    PATH=$OPATH
    cd; $emacsserver 1>/dev/null 2>&1 &
    echo 1>&2 "$progname: server starting: pid $!"
    until server_is_up; do sleep 1; done
    echo 1>&2 "$progname: server is up"
)

$emacsclient ${1+"$@"}

## end e
