#!/bin/sh

for arg; do
	case "$arg" in
	-*)	echo 1>&2 Option $arg ignored.
		shift;;
	esac
done

case $# in
2) A=$1 B=$2;;
*) echo "usage: "`basename $0`" OLD NEW"; exit 2 ;;
esac

e -c -F '((fullscreen . maximized))' -e '(ediff-files "'"$A"'" "'"$B"'")'
