#!/bin/bash

usage() {
	echo "usage: "`basename $0`" [OLD] NEW"
}

for arg; do
	case "$arg" in
	-*)	echo 1>&2 Option $arg ignored.
		shift;;
	esac
done

case $# in
1) if [ -r "$1"~ ]; then A="$1"~ B="$1"; else usage; exit 2; fi ;;
2) A=$1 B=$2     ;;
*) usage; exit 2 ;;
esac

if [ "WSL_DISTRO_NAME" ]; then
	e=~/cmd/ec;
else
	e=~/cmd/e;
fi

$e -c -F '((fullscreen . maximized))' -e '(ediff-files "'"$A"'" "'"$B"'")'
