#!/bin/bash

PATH=/usr/local/bin:/bin:/usr/bin

usage () {
	cat <<END
SYNOPSYS
$(basename $0) [glob]

DESCRIPTION
Compares (by diff -qs) the two most recent files names that match the optional
GLOB.  A null GLOB means the two most recent files in this directory, normally
not a meaningful operation.

The first line of output is the list of files found. If no files matched, that
is reported.  If only one file matches, /dev/null is interpolated ahead of it.
Else, the output of diff -qs is reported.

EXIT CODE
2, if no files match, or (CANTHAPPEN) too many files do (look at spaces in the
names). Else, whatever diff(1) returns.
END
}

case $1 in
-*)	usage; exit 0;;
esac

files=$(ls -tr "$@" | tail -2)
n_files=$(echo $files | wc -w)
case $n_files in
0)	echo no files match; exit 2;;
1)	files="/dev/null $files";;
2)	;;
*)	echo too many files match; exit 2;;
esac
echo $files
diff -qs $files

#end latest
