#!/bin/bash
## Copyright (C) 2014-2015 by Cesar A Quiroz, Ph.D.
## 3595 Granada Ave Unit 114 / Santa Clara, CA 95051 / USA
## All Rights Reserved Worldwide
## mailto:cesar.quiroz@gmail.com


## Logged execution: keep a single log of both fd 1 and fd 2
##
## Unless called "lx", runs make "$@"; else runs "$@"
##
## The runner arguments are prefixed by a default multithreading option
## (which can be overriden in the user-given arguments). This applies only
## to make runs.

progname=$(basename $0)

maxjobs=
type >/dev/null -p nproc && {
	maxjobs="-j$(expr 2 \* $(nproc))"
}

usage() {
	/bin/cat 1>&2 <<END_USAGE
USAGE: 
	lx <command invocation> 
	m <make arguments>

DESCRIPTION:
	lx runs the given simple command (not a pipeline);
	m runs make with the given arguments. The output 
	and error output of those runs are kept as a single
	.log file in the current working directory. The log
	file's name includes a timestamp in universal time
	(Z time zone), which permits accumulating logs.

	The log files can be used by Vim's quickfix feature
	(vim -q <logfile>), or as a compilation-mode buffer
	when read into Emacs. 
	
SEE ALSO:
	zlogs, to manage the log files as zip archives.
END_USAGE
}

case $# in 
0)	usage;
	exit 1;;
esac

case "$progname" in
lx)	runner=""
	runnerpfx="lx-"
	;;
*)	runner="make $maxjobs"
	runnerpfx="make-"
	;;
esac


# Is there a target (an arg that does not start with a dash)?

target=
for a; do
	case "$a" in
	-* | *=*)				;; # skip
	*) target=$(basename "$a"); break	;;
	esac
done

tstamp=$(/bin/date +%Y%m%d_%H%M%S)

case "$target" in
"")	tag="$tstamp"				;;
*)	tag="$target-$tstamp"			;;
esac

D=
[ -d "$LOGSDIR" ] && {
	case "$LOGSDIR" in
	*/)	D="$LOGSDIR"			;;
	*)	D="$LOGSDIR"/			;;
	esac
}

logfile="$D""$runnerpfx""$tag".log
case "$logfile" in
/*)						;;
*)	logfile="$(pwd)/$logfile"		;;
esac

{	printf '# -*- mode: Compilation; default-directory: \"%s\" -*-\n' $(pwd);
	echo $runner "$@"; echo;
	/usr/bin/time -p $runner "$@" 2>&1; rc=$?;
	[ -t ] && tset
	printf "\f\n";
	printf "RC:\t%d\n" $rc;
	printf "Log:\t%s\n" $(/bin/ls "$logfile");
} | tee "$logfile"

#end lx or m
