#!/bin/bash

parallel=-j

make $parallel all	&&
make $parallel doc	&&
make $parallel info	&&
make $parallel pdf	&&

sudo make $parallel install	&&
sudo make $parallel install-html	&&
sudo make $parallel install-info	&&
sudo make $parallel install-man	&&
sudo make $parallel install-pdf

##end make-and-install-git
