#!/bin/bash

project=$(basename $(pwd))
alternate=make-and-install-$project
found=$(type -t $alternate)

case $found in
alias|function|file)
	echo $alternate
	exec $alternate "$@";;
*)
	make -j $(nproc) && sudo make install;;
esac

##end make-and-install
