#!/bin/sh
## Copyright (C) 2015 by Cesar A Quiroz, Ph.D.
## 3595 Granada Ave Unit 114 / Santa Clara, CA 95051 / USA
## All Rights Reserved Worldwide
## mailto:cesar.quiroz@gmail.com

# (Re)build the cscope index files unconditionally.
# Works recursively down from the cwd; the index entries are relative to the cwd.
PATH=/bin:/usr/bin

cscope=${CSCOPECMD:-cscope}
cscope_files=${CSCOPEFILES:-cscope.files}
cscope_flags=${CSCOPEFLAGS:--bqu}
find=${FINDCMD:-find}

echo -q > "$cscope_files"
# don't use cscope for C++ :-(  ctags and gtags do a good-enough job
$find . -type f -name '*.[chyl]' >> "$cscope_files" &&
$cscope $cscope_flags

# end
