#!/bin/bash
## Copyright (C) 2008?-2015 by Cesar A Quiroz, Ph.D.
## 3595 Granada Ave Unit 114 / Santa Clara, CA 95051 / USA
## All Rights Reserved Worldwide
## mailto:cesar.quiroz@gmail.com

PATH=/bin:/usr/bin

# Run from the top of the project whose include directories you want to show
# to semantic.

# Set env EDE_SYSTEM_INCLUDE_PATHS for external dependences (not gcc, but, say,
# qt) that you want EDE to find. This variable is a list of directories, SPACE
# separatted.

elfile=$PWD/ede-cpproot.el
projname=$(basename $(pwd))
directories=${1+"$@"}
directories=${directories:-"."}

(
	echo "(require 'ede/cpp-root)"
	echo '(ede-cpp-root-project'
	echo ' :name "'"$projname"'"'
	echo ' :file "'"$elfile"'"'
	echo ' :include-path'
	echo " '("

	find -L $directories -type f \( \
	     -name '*.h' -o \
	     -name '*.hh' -o \
	     -name '*.hpp' -o \
	     -name '*.hxx'  \) | \
	grep -v /bld/ | \
	grep -v /lnk/ | \
	grep -v /run/ | \
	while read "h"; do d=`dirname $h`; echo $d; dirname "$d" ; done |
	sort |
	uniq |
	sed -e 's/^/   "\//' -e 's/$/"/'

	case "$EDE_SYSTEM_INCLUDE_PATHS" in
	"")	echo "  ))"
		;;
	*)
		echo '   )'
		echo ' :system-include-path'
		echo ' '"'"'('

		find -L "${EDE_SYSTEM_INCLUDE_PATHS}" -type f \( \
		     -name '*.h' -o \
		     -name '*.hh' -o \
		     -name '*.hpp' -o \
		     -name '*.hxx'  \) |
		while read "h"; do d=`dirname $h`; echo $d; dirname "$d" ; done |
		sort |
		uniq |
		sed -e 's/^/   "/' -e 's/$/"/'

		echo '   ))'
		;;
	esac
) > $elfile

# ls -l $elfile | sed -e 's/^/	/'

# end
