#!/bin/bash

CTAGS=${CTAGS:-/usr/bin/ctags}
GTAGS=${GTAGS:-/usr/local/bin/gtags}
CSCOPE=${CSCOPE:-/usr/bin/cscope}

QT=${QT:-/usr/include/x86_64-linux-gnu/qt5}
DIRSTOTAG=${DIRSTOTAG:-compass verific algochips}

set -x
cd /work/innergy

EDE_SYSTEM_INCLUDE_PATHS="$QT" \
	mk-ede-cpproot-el ${DIRSTOTAG}


find -L ${DIRSTOTAG} -type f -a \( \
	-name '*.c' -o -name '*.cpp' -o -name '*.cc' -o \
	-name '*.h' -o -name '*.hpp' -o -name '*.hh' -o \
	-name '*.l' -o -name '*.y' \
	\) -print | \
	grep -v '/bld/' | \
	grep -v '/lnk/' | \
	grep -v '/run/' | \
	sort -u > tagged.files

${CTAGS} -e -L- < tagged.files
${CTAGS} -L-    < tagged.files
${GTAGS} -I -f- < tagged.files

(printf %s -q; cat tagged.files) | ${CSCOPE} -bqu -i-
