#!/bin/bash

CTAGS=${CTAGS:-/usr/bin/ctags}
GTAGS=${GTAGS:-/usr/local/bin/gtags}
CSCOPE=${CSCOPE:-/usr/bin/cscope}

QT=${QT:-/usr/include/x86_64-linux-gnu/qt5}
DIRSTOTAG=${DIRSTOTAG:-compass verific algochips}

set -x
cd /work/innergy

EDE_SYSTEM_INCLUDE_PATHS="$QT" \
	mk-ede-cpproot-el ${DIRSTOTAG}

${CTAGS} -eR $DIRSTOTAG
${GTAGS} -I $DIRSTOTAG

find -L ${DIRSTOTAG} \( \
	-name '*.c' -o -name '*.cpp' -o -name '*.cc' -o \
	-name '*.h' -o -name '*.hpp' -o -name '*.hh' -o \
	-name '*.l' -o -name '*.y' \
	\) -print | \
	sort -u | \
	(echo -q; /bin/cat -) > cscope.files
${CSCOPE} -bqu
