#!/bin/sh
# $Header: overwrite,v 1.3 88/12/20 19:25:27 quiroz Locked $
# $Source: /u1/quiroz/src/cmd/overwrite/overwrite,v $
# overwrite:  copy standard input to standard output after EOF
# (From Kernighan and Pike, "The UNIX programming environment", p154)

opath=$PATH
PATH=/bin:/usr/bin

TMPDIR=${TMPDIR-/tmp}

case $# in
0|1)	echo 'Usage: overwrite file cmd [args]' 1>&2; exit 2
esac

file=$1; shift
new=$TMPDIR/overwr1.$$; old=$TMPDIR/overwr2.$$
trap 'rm -f $new $old; exit 1'  1 2 15		# clean up files

if PATH=$opath "$@" >$new			# collect input
then
	cp $file $old			# save original file
	trap '' 1 2 15			# we are committed, ignore signals
	cp $new $file
else
	echo "overwrite: $1 failed, $file unchanged" 1>&2
	exit 1
fi

rm -f $new $old
