#!/bin/sh
## Copyright (C) 2015 by Cesar A Quiroz, Ph.D.
## 3595 Granada Ave Unit 114 / Santa Clara, CA 95051 / USA
## All Rights Reserved Worldwide
## mailto:cesar.quiroz@gmail.com

PATH=/bin:/usr/bin:$HOME/cmd

rmtags
rm -f ede-cpproot.el ede-cpproot.elc

# end
