#!/bin/sh
## Copyright (C) 2015 by Cesar A Quiroz, Ph.D.
## 3595 Granada Ave Unit 114 / Santa Clara, CA 95051 / USA
## All Rights Reserved Worldwide
## mailto:cesar.quiroz@gmail.com

PATH=/bin:/usr/bin

fromCTAGS='
tags
'

fromETAGS='
TAGS
'

fromGTAGS='
GPATH
GRTAGS
GTAGS
'

fromMKID='
ID
'

fromCSCOPE='
cscope.files
cscope.in.out
cscope.out
cscope.po.out
'

rm -f $fromCTAGS
rm -f $fromETAGS
rm -f $fromGTAGS
rm -f $fromMKID
rm -f $fromCSCOPE

# end
