#!/bin/bash 

date; echo;

set -x
warns='PYTHONWARNINGS=ignore'
sudo $warns apt-file                   update
#sudo $warns apt-file -a i386           update
sudo $warns apt-get                    update
sudo $warns apt-get -y --with-new-pkgs upgrade
sudo $warns apt-get -y                 autoremove
sudo $warns apt-get -y                 autoclean

set +x
echo; date;

# end tidy-apt
