#!/bin/sh

date; echo;

sudo apt-file                   update
sudo apt-file -a i386           update
sudo apt-get                    update
sudo apt-get -y --with-new-pkgs upgrade
sudo apt-get -y                 autoremove
sudo apt-get -y                 autoclean

echo; date;

# end tidy-apt
