#!/bin/sh
# trash prints what clean(1) would remove

PATH=/usr/bin:/bin

default=',* \#* *~ .*~ *.BAK .*.BAK core a.out'

set -- `getopt vl $*`
if [ $? != 0 ]; then
    echo 1>&2 usage: `basename $0` '[-v|-l] [directory]'
    exit 1;
fi

verbose='2>/dev/null';
long=;

for arg in $*; do
    case $arg in
    -v) verbose=; shift;;
    -l) long='-lgs'; shift;;
    --) shift; break;;
    esac
done

case $# in
0)  ;;
1)  cd $1;;
*)  echo 1>&2 usage: `basename $0` '[-v|-l] [directory]'
    exit 1;;
esac

command="exec ls $verbose -a $long ${TRASH-${default}}"
eval $command

