#!/bin/sh

# upversion <filename>
# if <filename> exists, it is moved to a file with name <filename>.~N~
# for N greater than whatever exists already.
# else the file is created empty.

# Shares a lot of code with newversion, but I'd rather not make things
# even slower by factoring out the common code.

PATH=/usr/bin:/usr/ucb:/bin

if [ $# -ne 1 ]; then
        echo 1>&2 $0: needs exactly one argument, a filename
        exit 1
fi

if [ ! -f $1 ]; then
        > $1
        exit $?
fi

highest=`
        ls $1* |
        sed -n -e '/.*\.~\([0-9][0-9]*\)~$/s//\1/p' |
        sort -n -r |
        sed 1q
`
if [ "$highest" ]; then
    next=`expr $highest + 1`
else
    next=1
fi

cp -p $1 $1.~${next}~
