#!/bin/bash

usage() {
	local progname=$(basename $0)
	echo "usage: $progname [OLD] NEW"
	echo "       $progname BASE:in THEIRS:in YOURS:in [MERGED:out]"
}

flags=
for arg; do
	case "$arg" in
	-*)	flags+=" $arg"
		shift;;
	esac
done

A= B= C= D=
case $# in
1) if [ -r "$1"~ ]; then A="$1"~ B="$1"; else usage; exit 2; fi ;;
2) A=$1 B=$2 ;;
3) A=$1 B=$2 C=$3 ;;
4) A=$1 B=$2 C=$3 D=$3 ;;
*) usage; exit 2 ;;
esac
set - "$A" "$B" "$C" "$D"

vimdiff $flags $@
#end vdiff
