#!/bin/bash

dispatch=${xDISPATCH:-"$HOME/.x-dispatch"}

#DEFAULT_XTERM=sakura
DEFAULT_XTERM=gnome-terminal
xterm=${XTERM:-${DEFAULT_XTERM}}

xrows=${XROWS:-48}
xcols=${XCOLS:-110}

OPATH="$PATH"
PATH=/usr/bin:/bin

function usage {
  echo 1>&2 "Usage: " `basename $0` " [cmd [args...]]"
  echo 1>&2 "	Run _cmd_ (default, \$SHELL, currently '$SHELL') in a terminal,"
  echo 1>&2 "	the terminal is \$XTERM, which defaults to $DEFAULT_XTERM."
  echo 1>&2 "		(Your current setting is '$xterm'.)"
  echo 1>&2 "	passing the _args_ to _cmd_."
}

case $# in
1)
    case "$1" in
    -h*|--h*|-\?)
	usage; exit 0 ;;
    esac ;;
esac

who=${LOGNAME:-${USER:-'me'}}
where=`uname -n`
cmd=${1:-${SHELL:-'/bin/sh'}}
name=`basename $cmd`	# before remapping

[ -f $dispatch ] || touch $dispatch;
newcmd=`sed -n -e "/^$name	\(.*\)/s//\1/p" $dispatch`
cmd=${newcmd:-$cmd}

shift				# consume the cmd name
case $# in
0)	title="$who@$where  $name"		;;
1)	title="$name $1"			;;
2)	title="$name $1 $2"			;;
3)	title="$name $1 $2 $3"			;;
4)	title="$name $1 $2 $3 $4"		;;
5)	title="$name $1 $2 $3 $4 $5"		;;
*)	title="$name $1 $2 $3 $4 $5 $6 ..."	;;
esac

export PATH="$OPATH"

if [ "$INSIDE_EMACS" ]; then
	# Let the tools take their defaults, instead of whatever
	unset MANPAGER
	unset PAGER
fi

case "$xterm" in
gnome-terminal)
	#"$xterm" --geometry "$xcols"x"$xrows" -t "$title" -x $cmd ${1+"$@"} &
	"$xterm" 1>/dev/null 2>/dev/null --geometry="$xcols"x"$xrows" -- \
		 with-x-title "$title" $cmd ${1+"$@"}
	;;
sakura)
	"$xterm" -r "$xrows" -c "$xcols" -t "$title" -e $cmd ${1+"$@"} &
	;;
esac

##end x
