#!/bin/bash

dispatch=${xDISPATCH:-"$HOME/.x-dispatch"}

DEFAULT_XTERM=gnome-terminal
xterm=${XTERM:-${DEFAULT_XTERM}}

DEFAULT_PAGER="view -"
pager=${PAGER:-${DEFAULT_PAGER}}

xrows=${XROWS:-36}
xcols=${XCOLS:-82}

PATH=/usr/bin:/bin

function usage {
  echo 1>&2 "Usage: " `basename $0` " cmd [args...]"
  echo 1>&2 "	Run _cmd_ (not a function or alias) in a terminal, "
  echo 1>&2 "	the terminal is \$XTERM, which defaults to '$DEFAULT_XTERM'."
  echo 1>&2 "		(Your current setting is '$XTERM'.)"
  echo 1>&2 "	passing the _args_ to _cmd_ and displaying the results"
  echo 1>&2 "	using \$PAGER, which defaults to '$DEFAULT_PAGER'."
  echo 1>&2 "		(Your current setting is '$PAGER'.)"
}

case $# in
0)
    usage; exit 1 ;;
1)
    case "$1" in
    -h*|--h*|-\?)
        usage; exit 0 ;;
    esac ;;
esac

who=${LOGNAME:-${USER:-'me'}}
where=`uname -n`
cmd=$1
name=`basename $cmd`	# before remapping

[ -f $dispatch ] || touch $dispatch;
newcmd=`sed -n -e "/^$name	\(.*\)/s//\1/p" $dispatch`
cmd=${newcmd:-$cmd}

shift
case $# in
0)	title="$who@$where  $name"			;;
1)	title="@$where  $name $1"			;;
2)	title="@$where  $name $1 $2"			;;
3)	title="@$where  $name $1 $2 $3"			;;
4)	title="@$where  $name $1 $2 $3 $4"		;;
5)	title="@$where  $name $1 $2 $3 $4 $5"		;;
*)	title="@$where  $name $1 $2 $3 $4 $5 $6 ..."	;;
esac

tmpfn=${TMPDIR:-/tmp}/xo-"$who"$$

# auxiliary script deletes itself
echo >"$tmpfn" $cmd ${1+"$@"} \| $pager
echo >> "$tmpfn" /bin/rm -f "$tmpfn"

chmod +x "$tmpfn"
"$xterm" -t "$title" -x "$tmpfn"

# end of xo
