#!/bin/bash
## Copyright (C) 2015 by Cesar A Quiroz, Ph.D.
## 3595 Granada Ave Unit 114 / Santa Clara, CA 95051 / USA
## All Rights Reserved Worldwide
## mailto:cesar.quiroz@gmail.com

progname=$(basename $0)

zipname=""
dirname=""
zipfile=""

ZLOGSGLOB=${ZLOGSGLOB:-*.log}

PATH=/bin:/usr/bin

usage () {
	/bin/cat 1>&2 << END_USAGE
USAGE: 
	$progname [options] [zipname [dirname]]

DESCRIPTION
	Collect the \$ZLOGSGLOB (default \*.log) files in the current
	directory into a zip. The log files are added/updated in the
	zip.

	With no arguments, and no \$ZLOGSDIR: 

		The zipname is the basename of \$PWD, the dirname is \$PWD.
		Therefore, the default zip file is 

			\${PWD}/\$(basename \${PWD}).zip

	With no arguments, but \$ZLOGSDIR in the environment:

		The default dirname is the value of \$ZLOGSDIR, therefore:
			\${ZLOGSDIR}/\$(basename \${PWD}).zip

	With a zipname argument, but no dirname:

		If the zipname does not contain slashes, it is taken
		as-is and combined with the directory determined by the
		presence or absence of \$ZLOGSDIR.

		If the zipname starts with a slash, it is taken as-is,
		and no directory is determined. Any intermediate directories
		are created if needed.

		If the zipname contains slashes, it is interpreted relative
		to the directory determined depending on \$ZLOGSDIR. Any
		needed intermediate directories are created if needed.

	With both zipname and dirname present:

		The two arguments get concatenated, the concatenation is 
		used as-is.

OPTIONS
	-d
	--delete	Delete logs after zipping them

	-n
	--dry-run	Show, but not do, what would happen

	-l
	--list		list the logs zipped already

	-h
	--help		Succeed after printing this message to stdout.
END_USAGE
}

mk_zipfile_name () {
	zipname="$1"
	dirname="$2"
	case "$zipname" in
	/*)	zipfile="$zipname"
		mkdir -p $(dirname "$zipfile")
		;;
	*/*)	zipfile="$dirname/$zipname"
		mkdir -p $(dirname "$zipfile")
		;;
	*)	zipfile="$dirname/$zipname"
		;;
	esac
	echo $zipfile
}

case $# in
0)	usage; exit 1;;
esac

deleter=":"
interpreter="bash"
lister="ls -l"
zippy="zip -uv"
for arg in "$@"; do
	case "$arg" in
	-d|--delete)    deleter="rm -f"; lister=":"; shift;;
	-h|--help)	usage; exit 0;;
	-l|--list)      zippy="unzip -l"; deleter=":"; lister=":"; shift;;
	-n|--dry-run)   interpreter="cat"; shift;;
	esac
done

case "$#" in
0)	zipname=$(basename $PWD)
	dirname=${ZLOGSDIR:-$PWD}
	zipfile="$dirname/$zipname"
	;;
1)	zipname="$1";
	dirname="${ZLOGSDIR:-$PWD}"
	zipfile=$(mk_zipfile_name "$zipname" "$dirname")
	;;
2)	zipname="$1";
	dirname="$2";
	zipfile=$(mk_zipfile_name "$zipname" "$dirname")
	;;
*)	usage; exit 1
	;;
esac

case "$zipfile" in
*.zip)	;;
*)	zipfile="$zipfile".zip ;;
esac

cat <<EOF | $interpreter
$zippy ${zipfile} ${ZLOGSGLOB}
case \$? in
# Refer to the zip manual page for the meaning of 0 and 12 as exit codes.
0 | 12) $deleter ${ZLOGSGLOB}; echo; $lister ${ZLOGSGLOB} ;;
esac
EOF
echo
echo "zipfile:	$zipfile"

# end zlogs
