* [2016-04-12 Tue] Umbehauen on good inks and paper

German brands, three pens, Pelikan 4001. Nibs are custom flex-and-wet, Bock 1.1 and
Bock Medium.

No feathering, no bleed-thru, a touch of ghosting when a wet/flex nib is
used. All excellent--be mindful of drying time.


** Oxford

** Soennecken

** Brunnen

** Hammer

** Landré

** Rhodia dot pad / grid pad


* [2016-04-12 Tue] Unbehauen on BAD paper for inks

Moleskine (atrocious feathering and bleed-thru).




* [2016-04-12 Tue] Pelahale on papers for fountain pens
https://www.youtube.com/watch?v=Q8KDijH93m4&nohtml5=False

80 to 90 grams per square meter (gsm). Coating is normally needed (for
stability). Ideally acid-free, so they don't yellow right away.

The Rhodia should be premium (dark covers).

RECOMMENDED LIST arranged by price:

- Quo Vadis Habana large (B5, 6.25x9.25") US, uses Clairfontaine paper, 80sheets of 85gsm, $23, or $0.287/sheet.
- Rhodia webnotebook large (A5) of France, 96sheets of 90gsm, $24, $0.25/sheet.
- Crown Mill cotton (A5, 5.34x8.5") Belgian & French tablet, 50sheets of 100gsm, $11, or $0.22/sheet.
- Exacompta (A5, 5.5x8.25") of Paris, 100sheets of 100gsm, $15.50, or $0.155/sheet.
- Rhodia plain No.16 premium (A5) of France, 70 sheets of 90gsm, $7.25, $0.104/sheet.
- Clairefontaine clothbound (A5: 6x8.25", A6:4.25x6.75") of France, 96sheets of 90gsm, $9, or $0.094/sheet.
- Rhodia plain No.16 (A5) of France, 80sheets of 80gsm, $5.50, or $0.069/sheet. 

NOT RECOMMENDED LIST arranged by price:

- Midori MD large (A5, 6x8.25") of Japan, 88sheets of ~85gsm, $16.80, or $0.19/sheet.
- Tsubame (B5, 7x10") of Japan, 55sheets of ?80gsm, $5.95, or $0.108/sheet. 
- Leuchtturm 1917 (A5, 5.75x8.25") of Germany & Taiwan, 125sheets of ~80gsm, $13.49, $0.108/sheet.
- Moleskine (A5, 5.2x8.2") of Italy & China, 120sheets of 70gsm, $12.21, $0.102/sheet.
- Generic bookstore variety notebooks: C.R.Gibson (A5, 5.25x8") 120sheets of 70gsm, $10, $0.083/sheet.
- Compare to Mead Composition books: (B5, 7.5x9.75") China, 100sheets of
  70gsm, $1.75, $0.0175/sheet.

https://www.youtube.com/watch?v=XGjbvKQ1ghg&feature=youtu.be

'll show how I formulated my ideal paper traits: it comes down to just a few features.
----------------------------------------­-----------------------------
00:19 - I.Quick Summary
01:18 - II.Tomoe River Paper Review
03:31 - III.Paper Thickness Caliper measurements
06:40 - IV.Hand-made Tomoe-River mini-notebook for Midori Traveler's Notebook Passport size
08:01 - V.Expensive Japanese Metaphys mini-notebooks
09:59 - VI.Life Noble Japanese premium notebooks
----------------------------------------­----------------------------------
Paper Thickness Caliper Data: 
using Mitutoyo Absolute Digimatic CD-6" CSX
readings at temp: 77F, humidity 39%. 4+ readings each side of paper; 3 of 4 concordant, minimal squeeze to avoid indenting:

French Papers:
-Clairefontaine Triomphe letter 90gsm: 0.09mm
-Exacompta 100gsm 9930 A5: 0.14mm
-G.Lalo Verge de France A5: 0.13mm
-QuoVadis Habana large & small (Clairfont90gsm): 0.09mm
-Rhodia Webnotebook A5 90gsm: 0.09mm
-Rhodia Dot Pad 80gsm: 0.08mm
-Rhodia Premium Bloc R #18 blanc 90gsm: 0.09mm

Japanese Papers:
-Apica Premium CD A5, 85gsm: 0.09mm
-Apica 6a10 B5, 80gsm: 0.09mm
-Apica CD15 B5, 80gsm: 0.09mm
-Kokuyo Campus A5 MIO: 0.07mm
-Kokuyo Campus B5 Cyo-Bo: 0.11mm
-Life Noble N.36 A5: 0.09mm
-Maruman Septcouleur N572-10 A5 80gsm: 0.09 mm
-Maruman Edge Title A5 B: 0.08mm
-Maruman Mnemosyne 181 Imagination 80gsm: 0.09mm
-Maruman Mnemosyne Light N173: 0.09mm
-Metaphys 44110 blanc: 0.08mm
-Midori A5 MD journal 80gsm: 0.08mm
-Midori Traveler NB standard: 0.09mm
-Tomoe River "Seven Seas" cream notepad: 0.05mm

Other Papers:
-BanditApple Carnet Handy 80gsm: 0.12mm
-Fabriano Misto A5 85gsm: 0.10mm
-Hammermill 20lb copier paper 75gsm: 0.09mm
-Leuchtterm 1917 80gsm: 0.09mm
-Moleskine Cahier standard: 0.08mm
-Original Crown Mill Cotton A5 100gsm: 0.14mm
-Staples "CardStock": 0.24mm
-Staples 32lb Ivory paper: 0.15mm
-White Lines A5 80gsm: 0.09mm

----------------------------------------­-----------------
Quality Paper Pricing data at reference A5 size

QuoVadis Habana large (6.25"x9.25", 80sheets, 85gsm): 28.5cents/sheet
Rhodia WebNotebook A5 (5.5"x8.25", 96sheets 90gsm): 24.7cents/sheet
Rite in Rain ~A5 (4.75"x7.5", 80 sheets, waterproof): 22.4cents/sheet
California Republic Palomino Blackwing A5 (5"x8.25", 80sheets, 100gsm): 20.3cents/sheet
Midori MD large A5 (6"x8.25", 88sheets, 90gsm): 17cents/sheet
Apica Premium CD A5 notebook (5.8"x8.25", 96sheets, 85gsm): 16.9cents/sheet
Life Noble N.36 A5 notebook (5.8"x8.3",85gsm): 16cents/sheet
Exacompta (5.5x8.25, 100sheets, 100gsm): 14.5cents/sheet
Whitelines Perfect Bound A5 (5.8"x8.25", 48sheets, 80gsm): 13.8cents/sheet
Apica CD-11, A5 Notebooks (5.8"x8.3", 148mmx210mm, 28sheets, 75gsm): 11.3cents/sheet
Leuchtturm 1917 A5 (5.75"x8.25", 124sheets, 80gsm): 10.7cents/sheet
Fabriano EcoQua Dot A5 (5.8"x8.25", 90sheets, 85gsm): 10.5cents/sheet
Rhodia No.16 Premium "R" A5 (6"x8.25", 70sheets, 90gsm): 10.2cents/sheet
Tomoe River Seven Seas A5 (5.8"x8.3", 100sheet, 52gsm): 10cents/sheet
Kokuyo Campus MIO A5 (5.8"x8.3", 80 sheets, 75gsm): 9.7cents/sheet
Clairefontaine clothbound A5 (6"x8.25", 96sheets of 90gsm): 9.5cents/sheet
Maruman Sept Couleur A5 (5.8"x8.3", 80 sheets, 80gsm): 9.4cents/sheet
Maruman Mnemosyne A5 (5.8"x8.3", 80sheets, 80gsm): 9.4cents/sheet



