#!/bin/bash

# Git -- run in /work

## cedet
git clone http://git.code.sf.net/p/cedet/git cedet

## dircolors-solarized
git clone https://github.com/seebi/dircolors-solarized.git

## emacs
git clone git://git.savannah.gnu.org/emacs

## git
git clone https://github.com/git/git.git

## global
cvs -d:pserver:anonymous@cvs.sv.gnu.org:/sources/global co .

## gnome-terminal-colors-solarized
git clone https://github.com/Anthony25/gnome-terminal-colors-solarized.git

## iverilog
git clone https://github.com/steveicarus/iverilog.git

## solarized-gedit
git clone git://github.com/mattcan/solarized-gedit.git

## solarized-xresources
git clone https://github.com/solarized/xresources.git

## stable-linux
git clone https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git

## vim
git clone https://github.com/vim/vim.git

## xfce4 Terminal
git clone https://github.com/sgerrand/xfce4-terminal-colors-solarized.git

## end
