function PageInfo(){function y(a){for(var b=[];a;)b.unshift(a),a=a.parentNode;return b}function t(a,b){var c=document.location.host;if(z[c]){var f=document.querySelector(z[c].container);if(f){var g=f.querySelectorAll(z[c].include);if(g&&0<g.length){var e=g[g.length-1].nextElementSibling;d=document.createElement("div");for(f=0;f<g.length;f++)d.appendChild(g[f]);e.parentNode.insertBefore(d,e)}}}if(!d&&A[c])for(f=0;f<A[c].length;f++){if(g=document.querySelector(A[c][f])){d=g;break}}else if(-1!=R.indexOf(c)){c=
document.getElementsByTagName("img");f=null;for(e=g=0;e<c.length;e++){var l=window.getComputedStyle(c[e]),h=parseInt(l.width),l=parseInt(l.height),h=h*l;h>g&&(f=c[e],g=h)}d=f}!d&&k&&(d=document.querySelector(n[k].content),d&&""!=d.textContent.trim()||(d=document.createElement("div"),document.body.insertBefore(d,document.body.firstChild)));!d&&/\.(jpe?g|gif|png)$/.test(document.location.href)&&(g=document.getElementsByTagName("img")[0])&&g.parentNode===document.body&&(d=g);if(!d&&"frameset"==document.body.nodeName.toLowerCase()){B=
!0;c=document.getElementsByTagName("frame");f=null;for(e=g=0;e<c.length;e++)c[e].width&&c[e].height&&(h=c[e].width*c[e].height,h>g&&(f=c[e],g=h));(c=f)&&c.contentDocument&&c.contentDocument.documentElement&&(C=c,d=c.contentDocument.documentElement)}if(!d&&a&&a._elements&&a._elements.length){d=a._elements[0];if(1<a._elements.length)if(c=a._elements,c.length)if(1==c.length)d=c[0];else{f=y(c[0]);e=null;for(g=1;g<c.length;g++){e=y(c[g]);h=null;for(l=0;l<f.length;l++)if(f[l]===e[l])h=f[l];else break;e=
h;f=y(e)}d=e}else d=null;d.nodeType===Node.TEXT_NODE&&(d=d.parentNode)}d||(d=document.body);D=!0;b()}function S(){!d||d.parentNode&&d.getBoundingClientRect&&0!=d.getBoundingClientRect().width||(d=null,E=[],q=[],D=!1);D?1048576<document.body.innerHTML.length?(log.warn("Page over 1mb, skipping article detection."),t(null,m)):m():"function"==typeof initClearlyComponent__detect&&"function"==typeof initClearlyComponent__next?(u={callbacks:{finished:function(a){a&&a._html&&q.push(a._html);v.start();t(a,
m)}},window:window,jQuery:window.jQuery},(u=initClearlyComponent__detect(u))?(v={callbacks:{newPageFound:function(a){q.push(a._html);E.push(a._elements[0]);r&&r(a._html,a._url,q.length)}},settings:{onCreateNextPagesContainerUseThisId:"evernoteClearlyNextContainer"},detectComponentInstance:u},(v=initClearlyComponent__next(v))?(v.createNextPagesContainer(),u.start()):(log.warn("failed to initiate clearly next component"),t(null,m))):(log.warn("failed to initiate clearly detect component"),t(null,m))):
(log.warn("Couldn't find clearly!"),t(null,m))}function F(a){m=a;S()}function G(a,b){r=b;F(function(){a(d);r&&r(null,null,q.length)});if(d)return d}function K(){var a=w();s=[];if(a)for(var b=0;b<a.rangeCount;b++){var c=a.getRangeAt(b);s[b]=c}}function w(){var a=window.getSelection();if(a&&a.rangeCount&&!a.isCollapsed)return a;for(var a=[],b=document.getElementsByTagName("iframe"),c=0;c<b.length;c++)a.push(b[c]);b=document.getElementsByTagName("frame");for(c=0;c<b.length;c++)a.push(b[c]);b=document.location.href.replace(/^(https?:\/\/.*?)\/.*/i,
"$1").toLowerCase();for(c=0;c<a.length;c++)if(!a[c].src||a[c].src.toLowerCase().substr(0,b.length)===b)try{var f=a[c].contentDocument;if(f){var g=f.getSelection();if(g&&g.rangeCount&&!g.isCollapsed)return L=!0,C=a[c],g}else log.warn("iframe contained no Document object.")}catch(e){}return null}function T(){var a=window.getSelection();a.removeAllRanges();for(var b=0;b<s.length;b++)a.addRange(s[b])}function p(a,b,c,f,g,e){if(a.nodeType==Node.TEXT_NODE)return f||!k?(a=U(a,g),e=e?GlobalUtils.removePunctuation(a.trim()).replace(/\s+/g,
" "):a.trim().replace(/\s+/g," ")," "===e||""===e?b:b+" "+e):b;var d=["script","noscript","style"];if(a.nodeType==Node.ELEMENT_NODE&&-1==d.indexOf(a.nodeName.toLowerCase())){if(/^evernote.+Tools$/.test(a.id))return b;for(d=0;d<a.childNodes.length;d++){if(k){var h;h=a.childNodes[d];var m=n[k].bannedSubelements;h=m&&h.webkitMatchesSelector&&h.webkitMatchesSelector(m)?!0:!1;if(h)continue;h=n[k].allowedElements;h=a.webkitMatchesSelector&&a.webkitMatchesSelector(h)?!0:!1;b=h||f?g?p(a.childNodes[d],b,c,
!0,g,e):p(a.childNodes[d],b,c,!0,a,e):p(a.childNodes[d],b,c,!1,null,e)}else b=p(a.childNodes[d],b,c,!1,null,e);if(b.length>c)break}}return b}function U(a,b){var c=a.textContent;if(k){var f;if("Baidu"==k){if(f=b.parentNode.parentNode.querySelector(".g"))f=f.textContent}else if("Yandex"==k||"YandexRU"==k){if(f=b.parentNode.querySelector(".b-serp-item__title-link, .serp-item__title-link"))f=f.href}else f=b.href;if(f){var d={wikipedia:/(.*)[-|\u2013|\u2014]/,youtube:/(.*)[-|\u2013|\u2014]/,facebook:/(.*)\|/,
wiktionary:/(.*)-\sWiktionary/,stumbleupon:/(.*)\|\sStumbleUpon\.com/},e;for(e in d)if(RegExp(e).test(f)){var l=d[e].exec(c);if(l)return b.setAttribute("sawdivider",!0),l[1];if(b.getAttribute("sawdivider"))return""}}if(/(\d+\slikes)|(\d+\stalking\sabout\sthis)/.test(c))return c.replace(/(\d+\slikes)|(\d+\stalking\sabout\sthis)/g," ");if(/Definition from Wiktionary, the free dictionary. Jump to: navigation, search/.test(c))return c.replace(/Definition from Wiktionary, the free dictionary. Jump to: navigation, search/g,
" ")}return c}function M(){var a=document.title;if(k)if(n[k].titleTrim)a=n[k].titleTrim(a);else var b=a.split(" - "),a=a.replace(" - "+b[b.length-1],"");return a.trim()}function N(){if(k&&document.querySelector(n[k].searchBox)){var a=document.querySelector(n[k].searchBox).value.trim();if(0<a.length)return a}return null}function O(a,b){var c="",c=w();if(a)G(function(a){b(p(a,"",510,!1,null,!1))});else{if(c){var c=c.getRangeAt(0).cloneContents(),f=document.createElement("div");f.appendChild(c);c=p(f,
"",5E3,!1,null,!0)}else c=d?p(d,"",5E3,!1,null,!0):p(document.body,"",5E3,!1,null,!0);return c=M()+" "+c}}function P(){if(document.querySelector("embed[type='application/pdf']"))return document.querySelector("embed[type='application/pdf']").src;if(/^https?:\/\/docs\.google\.com\/viewer\?url=.+/.test(document.location.href))for(var a=0;a<document.scripts.length;a++){if(/gviewApp\.setFileData/.test(document.scripts[a].innerText)){if(/mimeType.+application\/pdf/.test(document.scripts[a].innerText))return a=
/^https?:\/\/docs\.google\.com\/viewer\?url=(.+?)(?:$|&)/.exec(document.location.href),decodeURIComponent(a[1]);break}}else if(H())return H();return null}function x(){return/^https:\/\/mail\.google\.com\/mail\//.test(document.location.href)?!0:!1}function Q(){return x()&&0<document.querySelectorAll("span > div > span > [src='images/cleardot.gif']").length?!0:!1}function H(){var a=/^chrome-extension:\/\/(?:encfpfilknmenlmjemepncnlbbjlabkc|oemmndcbldboiebfnladdacbdfmadadm)\/(.+)/.exec(document.location.href);
return a?a[1]:null}var m,r,u,v,A={"penny-arcade.com":["div.contentArea > div.comic > img"],"aspicyperspective.com":["div.entry-content"],"thewirecutter.com":["div#content"],"katespade.com":["div#pdpMain"],"threadless.com":["section.product_section"],"yelp.com":["div#bizBox"],"flickr.com":["div#photo"],"instagr.am":["div.stage > div.stage-inner"],"stackoverflow.com":["div#mainbar"],"makeprojects.com":["div#guideMain"],"cookpad.com":["div#main #recipe"],"imgur.com":["div.image"],"smittenkitchen.com":["div.entry"],
"allrecipes.com":["div#content-wrapper"],"qwantz.com":["img.comic"],"questionablecontent.net":["img#strip"],"cad-comic.com":["div#content"],"twitter.com":[".permalink","div.content-main"],"blog.evernote.com":[".post"]},z={"blog.evernote.com":{container:"#page-wrap > section > article",include:"h2, .p-meta, .post-meta, .thumbnail, .art-content"},"kirei.biglobe.ne.jp":{container:"div#main",include:".recipeTitle, .recipeMain, #howTo"},"nomnompaleo.com":{container:"section article.text",include:"header, section"},
"foodnetwork.com":{container:"#fn-w",include:".rcp-head, .tabnav, #recipe-lead, .w-inner, .body-text"}},R=["xkcd.com"],n={Baidu:{regex:/^https?:\/\/([^.\/]+\.)?baidu\.(com|cn)\/s/i,content:"#container",searchBox:"input[name=wd]",allowedElements:"h3.t a[data-click], .f font[size='-1']",bannedSubelements:"span.g, .m, .c",titleTrim:function(a){var b=/(.+)_\u767E\u5EA6\u641C\u7D22/;return b.test(a)?b.exec(a)[1]:a}},Bing:{regex:/^https?:\/\/([^.\/]+\.)?bing\.com\/search/i,content:"#results_container, #b_results",
searchBox:"input[name=q]",allowedElements:"div.sb_tlst a, div.sa_mc p, .b_algo h2 a, .b_algo .b_caption p"},Daum:{regex:/^https?:\/\/search\.daum\.net\/search/i,content:"#mArticle .inner_article",searchBox:"input[name=q]",allowedElements:".coll_cont ul .wrap_tit a, .coll_cont ul .f_eb.desc",titleTrim:function(a){var b=/(.+)\s\u2013/;return b.test(a)?b.exec(a)[1]:a}},Google:{regex:GlobalUtils.buildGoogleRegEx(),content:"#rso",searchBox:"input[name=q][type=hidden]",allowedElements:"a.l, span.st",bannedSubelements:"span.f"},
Naver:{regex:/^https?:\/\/search\.naver\.com\/search\.naver/i,content:"#content",searchBox:"input[name=query]",allowedElements:".type01 dt a, .type01 dd:not(.txt_inline):not(.txt_block):not(.review):not([style*='display:none'])",titleTrim:function(a){var b=/(.+)\s\u003A/;return b.test(a)?b.exec(a)[1]:a}},Yahoo:{regex:/^https?:\/\/([^.\/]+\.)*yahoo\.com\/s(earch|\?)/i,content:"#main",searchBox:"input[name=p]",allowedElements:".yschttl.spt[id], .abstr"},YahooCN:{regex:/^https?:\/\/([^.\/]+\.)*yahoo\.cn\/s(earch|\?)/i,
content:".content",searchBox:"input[name=q]",allowedElements:"h3.title a, .desc",titleTrim:function(a){var b=/(.+)_\u7F51\u9875\u641C\u7D22/;return b.test(a)?b.exec(a)[1]:a}},YahooJP:{regex:/^https?:\/\/([^.\/]+\.)*yahoo\.co\.jp\/s(earch|\?)/i,content:"#WS2m ul",searchBox:"input[name=p]",allowedElements:"#WS2m .hd h3 a, #WS2m .bd p",bannedSubelements:"#WS2m .bd p.dlink",titleTrim:function(a){var b=/\u300C(.+)\u300D/;return b.test(a)?b.exec(a)[1]:a}},Yandex:{regex:/^https?:\/\/([^.\/]+\.)?yandex\.com\/yandsearch/,
content:".b-serp2-list.b-serp.i-bem.b-serp_js_inited.b-serp2-list_js_inited",searchBox:"input[name=text]",allowedElements:".b-serp2-item__title-link, .b-serp2-item__text",bannedSubelements:".b-serp2-item__from",titleTrim:function(a){var b=/(.+)\s+\u2014/;return b.test(a)?b.exec(a)[1]:a}},YandexRU:{regex:/^https?:\/\/([^.\/]+\.)?yandex\.ru\/yandsearch/,content:".b-serp-list",searchBox:"input[name=text]",allowedElements:".b-serp-item__wrapper .b-serp-item__title-link, .b-serp-item__text",bannedSubelements:".b-serp-item__from",
titleTrim:function(a){var b=/(.+)\s+\u2014/;return b.test(a)?b.exec(a)[1]:a}}},V=Boolean(0<document.getElementsByTagName("img").length),W=document.width,X=document.height,Y=document.location.href,d=null,E=[],q=[],L=!1,B=!1,C=null,I=null,D=!1,s=[],k=null,J;for(J in n)if(n[J].regex.test(document.location.href)){k=J;break}Browser.addMessageHandlers({getInfo:function(a,b,c){"undefined"!=typeof SAFARI&&SAFARI&&!a.sendToTab&&0<s.length&&null==w()&&T();F(function(a){a=w();a={containsImages:V,documentWidth:W,
documentHeight:X,url:Y,selection:null!==a||0<s.length,selectionIsInFrame:L,documentLength:document.body.textContent.length,article:null!=d,recommendationText:O(!1),query:N(),searchEngine:k,favIconUrl:I,documentIsFrameset:B,pdf:P(),gmailThread:Q(),gmail:x()};Browser.sendToExtension({name:"simSearch_receivePageInfo",info:a})})},setFavIconUrl:function(a,b,c){I=a.favIconUrl}});"undefined"!=typeof SAFARI&&SAFARI&&(window.addEventListener("mouseup",K),Browser.addKeyboardHandlers({"65 + 91":K}));this.getBiggestImage=
function(a){G(function(b){b=b?b.querySelectorAll("img"):document.querySelectorAll("img");for(var c=0,d=0,g,e=0;e<b.length;e++){var k=b.item(e).width,h=b.item(e).height;k*h>d*c&&(c=h,d=k,g=b.item(e).src)}a({src:g,width:d,height:c})})};this.getDefaultArticle=G;this.getCanonicalUrl=function(){if(!x()){var a=document.querySelector("link[rel='canonical']");if(a)return a.href}return null};this.getCleanArticle=function(a,b){r=b;F(function(){a(q)})};this.getAdditionalPages=function(a){return E};this.getSelection=
w;this.getSelectionFrame=function(){return C};this.getPdfUrl=P;this.getRecommendationText=O;this.getSearchQuery=N;this.getTitle=M;this.isGmail=x;this.isGmailThread=Q;this.getRealUrlFromOperaPdfViewerUrl=H;this.__defineGetter__("documentIsFrameset",function(){return B});this.__defineGetter__("favIconUrl",function(){return I});Object.preventExtensions(this)}Object.preventExtensions(PageInfo);
