var Log={useConsole:!0,maxLogSize:104857600};SAFARI&&(Log.useConsole=!0);Object.preventExtensions(Log);
function LogWriter(d){function l(){var a=new Date,b=a.getFullYear().toString(),c=(a.getMonth()+1).toString(),a=a.getDate().toString();1==c.length&&(c="0"+c);1==a.length&&(a="0"+a);return"en_log_"+(b+"-"+c+"-"+a)+".log"}function f(a){-1==g.indexOf(a)&&(g.push(a),Persistent.set(p,g),g.length>v&&h())}function k(a){q=!1;console.error("Failed to delete file!");setTimeout(h,36E5)}function h(){!q&&g.length>v&&(q=!0,m?m.getFile(g[0],{create:!1},e,k):n.root.getFile(g[0],{create:!1},e,k))}function e(a){a.remove(r,
k)}function r(){g.shift();Persistent.set(p,g);q=!1;h()}function a(a){n=a;d?n.root.getDirectory(d,{create:!0},function(a){m=a;h();b()},c):(h(),b())}function c(a){SAFARI||console.error("Failed to init FileSystem. Logs will not be saved.");w=!1}function b(){n&&s.length&&!t&&(t=!0,z())}function u(){console.warn("Error looking up file.");b()}function z(){var a=s.shift(),b=a[0],c=a[1],a=l();f(a);m?m.getFile(a,{create:!0},function(a){x(a,b,c)},u):n.root.getFile(a,{create:!0},function(a){x(a,b,c)},u)}function x(a,
b,c){a.createWriter(function(a){a.onwriteend=y;a.onerror=y;a.seek(a.length);var d=new Blob([(new Date).toTimeString()+" ("+b+") "+c+"\r\n"],{type:"text/plain"});a.write(d)},u)}function y(a){t=!1;b()}var n=null,m=null,w=!0,t=!1,s=[],p="logFileList";d&&(p=d+"LogFileList");var v=31,g=Persistent.get(p);g||(g=[]);var q=!1;SAFARI?c():webkitRequestFileSystem(PERSISTENT,Log.maxLogSize,a,c);this.write=function(a,c){w&&(s.push([a,c]),b())};Object.preventExtensions(this)}Object.preventExtensions(LogWriter);
function LogDispatcher(){function d(d,k,h){SAFARI||Browser.sendToExtension({name:d,message:k,path:l,error:h.stack})}var l=document.location.href.replace(/^.*?:\/\/\w+(\/.*?)(\?.*)?$/,"$1");this.error=function(f){d("log_error",f,Error())};this.exception=function(f){d("log_exception",f,Error())};this.log=function(f){d("log_log",f,Error())};this.warn=function(f){d("log_warn",f,Error())};Object.preventExtensions(this)}Object.preventExtensions(LogDispatcher);
function LogReceiver(){function d(a,c,b,d,f){c=c?c:r;var e=null;"string"!=typeof a&&f&&(a.filename&&(e=a.filename.replace(/^(chrome|safari)-extension:\/\/\w+/,"")),a=a.stack||a.trace||JSON.stringify(a));a=c+": "+a;f&&(a+=" at "+e);if(b){d||(a+="\r\n");f=a;if(b&&b.stack){b=b.stack.split(/\n+/);2<b.length&&(b.shift(),b.shift());for(e=0;e<b.length;e++)b[e]=b[e].replace(/^(.*\()(chrome|safari)-extension:\/\/\w+(\/.*)$/,"$1$3");d?(b[0].match(/^\s+at\s+(chrome|safari)-extension/)&&(b[0]=b[0].replace(/^\s+(at)\s+(chrome|safari)-extension:\/\/\w+(\/.*)$/,
" $1 $3")),d=b[0]):d=b.join("\r\n")}else d="";a=f+d}return a}function l(a,c,b){a=d(a,c,b);Log.useConsole&&console.error(a);e&&e.write("ERROR",a)}function f(a,c){var b=d(a,c,!1,!0,!0);Log.useConsole&&console.error(b);e&&e.write("EXCEPTION",b)}function k(a,c,b){a=d(a,c,b,!0);Log.useConsole&&console.log(a);e&&e.write("LOG",a)}function h(a,c,b){a=d(a,c,b);Log.useConsole&&console.warn(a);e&&e.write("WARN",a)}var e=new LogWriter,r=document.location.href.replace(/^.*?:\/\/\w+(\/.*?)(\?.*)?$/,"$1");Browser.addMessageHandlers({log_error:function(a,
c,b){l(a.message,a.path,{stack:a.error})},log_exception:function(a,c,b){f(a.message,a.path,{stack:a.error})},log_log:function(a,c,b){k(a.message,a.path,{stack:a.error})},log_warn:function(a,c,b){h(a.message,a.path,{stack:a.error})}});this.error=function(a){l(a,null,Error())};this.exception=function(a){f(a,null)};this.log=function(a){k(a,null,Error())};this.warn=function(a){h(a,null,Error())};Object.preventExtensions(this)}Object.preventExtensions(LogReceiver);var log;
log=document.location.href.match(/background\.html$/)?new LogReceiver:new LogDispatcher;
