#!/bin/sh

xargs sudo apt-get purge -y <<\End
libruby2.7
postgresql-client-13
thunderbird
thunderbird-gnome-support
postgresql-13
libepsilon1
libdvdcss2
postgresql-doc-13
subversion-tools
ruby-wirble
libfam0
gitlab-workhorse
libsvn1
r-cran-int64
libdvdcss-dev
libnetbeans-cvsclient-java
libxz-java-doc
libssl1.1
ruby-svn
r-cran-rsprng
libsvn-doc
subversion
libicu67
libsvn-dev
End
