#!/bin/csh -f
#
# auxiliary script for ci-all, takes care of ci'ing a single file.  
# usage is `ci-it [OPTIONS] FILENAME'
set basename=/usr/bin/basename
set ci=ci

if ( $#argv == 0 ) then
   echo "`$basename $0` [ci options] working-file-name";
   exit 1;
else
   set rcsfile=$argv[$#argv],v;
   exec $ci $* $rcsfile;
endif

