;;; docstr-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from docstr.el

(autoload 'docstr-mode "docstr" "\
Minor mode `docstr-mode'.

This is a minor mode.  If called interactively, toggle the
`DocStr mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `docstr-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(put 'global-docstr-mode 'globalized-minor-mode t)
(defvar global-docstr-mode nil "\
Non-nil if Global Docstr mode is enabled.
See the `global-docstr-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `global-docstr-mode'.")
(custom-autoload 'global-docstr-mode "docstr" nil)
(autoload 'global-docstr-mode "docstr" "\
Toggle Docstr mode in all buffers.
With prefix ARG, enable Global Docstr mode if ARG is positive; otherwise,
disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Docstr mode is enabled in all buffers where `docstr--turn-on-docstr-mode' would
do it.

See `docstr-mode' for more information on Docstr mode.

(fn &optional ARG)" t)
(autoload 'docstr-supports-p "docstr" "\
Return non-nil if current `major-mode' supports by `docstr'.")
(autoload 'docstr-major-modes "docstr" "\
List of `major-mode' that supports document string.")
(register-definition-prefixes "docstr" '("docstr-"))


;;; Generated autoloads from docstr-actionscript.el

(register-definition-prefixes "docstr-actionscript" '("docstr-"))


;;; Generated autoloads from docstr-c.el

(register-definition-prefixes "docstr-c" '("docstr-"))


;;; Generated autoloads from docstr-c++.el

(register-definition-prefixes "docstr-c++" '("docstr-"))


;;; Generated autoloads from docstr-csharp.el

(register-definition-prefixes "docstr-csharp" '("docstr-"))


;;; Generated autoloads from docstr-faces.el

(autoload 'docstr-faces-apply "docstr-faces" "\
Apply standard document string faces.")
(register-definition-prefixes "docstr-faces" '("docstr-faces-"))


;;; Generated autoloads from docstr-go.el

(register-definition-prefixes "docstr-go" '("docstr-"))


;;; Generated autoloads from docstr-groovy.el

(register-definition-prefixes "docstr-groovy" '("docstr-"))


;;; Generated autoloads from docstr-java.el

(register-definition-prefixes "docstr-java" '("docstr-"))


;;; Generated autoloads from docstr-js.el

(register-definition-prefixes "docstr-js" '("docstr-"))


;;; Generated autoloads from docstr-key.el

(register-definition-prefixes "docstr-key" '("docstr-key-"))


;;; Generated autoloads from docstr-lua.el

(register-definition-prefixes "docstr-lua" '("docstr-"))


;;; Generated autoloads from docstr-objc.el

(register-definition-prefixes "docstr-objc" '("docstr-"))


;;; Generated autoloads from docstr-php.el

(register-definition-prefixes "docstr-php" '("docstr-"))


;;; Generated autoloads from docstr-python.el

(register-definition-prefixes "docstr-python" '("docstr-"))


;;; Generated autoloads from docstr-ruby.el

(register-definition-prefixes "docstr-ruby" '("docstr-"))


;;; Generated autoloads from docstr-rust.el

(register-definition-prefixes "docstr-rust" '("docstr-"))


;;; Generated autoloads from docstr-scala.el

(register-definition-prefixes "docstr-scala" '("docstr-"))


;;; Generated autoloads from docstr-swift.el

(register-definition-prefixes "docstr-swift" '("docstr-"))


;;; Generated autoloads from docstr-typescript.el

(register-definition-prefixes "docstr-typescript" '("docstr-"))


;;; Generated autoloads from docstr-util.el

(register-definition-prefixes "docstr-util" '("docstr-"))


;;; Generated autoloads from docstr-writers.el

(register-definition-prefixes "docstr-writers" '("docstr-writers-"))

;;; End of scraped data

(provide 'docstr-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; docstr-autoloads.el ends here
