function GmailClipper(){function q(a){return a.replace(/(,{2,})/g,function(a){return a.split("").join("null")}).replace(/(\[,|,\])/g,function(a){return a.replace("[","[null").replace("]","null]")})}function r(a,d,g,c,h,f){var b=new XMLHttpRequest;b.open("POST",a);b.baseUrl=a;b.ik=d;b.threadId=g;b.numRetryMsgs=c.length;b.thread=h;b.threadingEnabled=f;b.onreadystatechange=function(){if(4==this.readyState)if(200==this.status){for(var a=this.response.substr(this.response.search(/\d/)).split(/\d+\n/),
b=[],c=0;c<a.length;c++)if(!(""==a[c].trim()||0>a[c].indexOf('"ms"'))){var h=q(a[c]);try{for(var f=JSON.parse(h),d=0;d<f.length;d++){var e=f[d];if("ms"==e[0]&&2<=e[3]&&4>=e[3]){var g=e[1],m=new GmailMessage(this.baseUrl);e[13]?(m.setAuthorInfo(e[5],e[6]),this.thread.setSubject(e[13][21]),m.setBody(e[13][6]),this.thread.addParticipants([[e[5],e[6]]]),this.thread.addParticipants(e[13][9][1]),this.thread.addParticipants(e[13][9][0]),m.addAttachments(e[13][7][0]),m.setDate(e[24])):b.push(g);this.thread.addMessage(m,
g)}}}catch(n){log.error("\n"+n.stack);log.log(h);l(null,"could not parse. check console for more details");return}}0<b.length&&0===this.numRetryMsgs?r(this.baseUrl,this.ik,this.threadId,b,this.thread,this.threadingEnabled):(0<b.length&&this.thread.removeMessages(b),l(this.thread))}else log.error("could not download gmail thread "+this.threadId+" with ik="+this.ik+" because of ("+this.status+") "+this.response),l(null,"could not download gmail thread "+this.threadId+" with ik="+this.ik+" because of ("+
this.status+") "+this.response)};b.setRequestHeader("Content-type","application/x-www-form-urlencoded");a="ik="+b.ik+"&ui=2&view=cv&ser=1&th="+b.threadId+"&pcd=1&mb="+(b.threadingEnabled?"0":"1")+"&rt=c";a=0<c.length?a+("&msgs="+c.join(",")+"&search=inbox"):a+"&search=query";b.send(a)}function n(a,d,g){var c=new XMLHttpRequest;c.open("POST",a);c.baseUrl=a;c.ik=d;c.onreadystatechange=function(){if(4==this.readyState)if(200==this.status)try{var a=this.response.substr(this.response.search(/\d/)).split(/\d+\n/),
c=!0,b=0;a:for(;b<a.length;b++)if(!(""==a[b].trim()||0>a[b].indexOf('"p"'))){var d=JSON.parse(q(a[b])),k=0;for(;k<d.length;k++)if("p"==d[k][0]){var p=0;for(;p<d[k][1].length;p++)if("bx_vmb"==d[k][1][p][0]){c=0==d[k][1][p][1];break a}}}g(this.baseUrl,this.ik,c)}catch(n){log.error("could not parse the settings response.\n"+n.stack),log.log(this.response),l(null,"could not parse settings. check internal clipper logs for more details")}else log.error("could not download settings from baseUrl="+this.baseUrl+
", ik="+this.ik+" with status ("+this.status+") "+this.response),g(this.baseUrl,this.ik,!0)};c.setRequestHeader("Content-type","application/x-www-form-urlencoded");c.send("ik="+d+"&view=pu&rt=c")}var l;window.addEventListener("message",function(a){"receiveGmailIk"==a.data.name&&(/mail\/$/.test(a.data.baseUrl)&&(a.data.baseUrl+="u/0/"),n(a.data.baseUrl,a.data.ik,function(d,g,c){var h=null;if(/#.+?.*\/(.+?)($|\?)/.test(window.location.href))h=/#.+?.*\/(.+?)($|\?)/.exec(window.location.href)[1];else for(var f=
document.querySelectorAll("[class^=m], [class*=' m']"),b=0;b<f.length;b++)if(/(\s|^)m([^\s]{5,})/.test(f[b].className)){h=/(\s|^)m([^\s]{5,})/.exec(f[b].className)[2];break}h?(f=new GmailThread,f.setUser(a.data.user.name,a.data.user.email),r(d,g,h,[],f,c)):(log.error("could not find thread Id for email: "+window.location.href),l(null,"could not find thread id. check clipper logs for more details"))}))});this.getThread=function(a){l=a;a=document.createElement("script");a.id="evernoteGmailScript";a.innerText=
'for (var i = 0; i < window.GLOBALS[17].length; i++) {if (window.GLOBALS[17][i] && window.GLOBALS[17][i][0] === "mla") {for (var j = 0; j < window.GLOBALS[17][i][1].length; j++) {if (window.GLOBALS[17][i][1][j][0] === window.GLOBALS[10]) {window.postMessage({name: "receiveGmailIk",baseUrl: window.GLOBALS[31],ik: window.GLOBALS[9],user: { email: window.GLOBALS[10], name: window.GLOBALS[17][i][1][j][4] }}, "*");break;}}}}document.body.removeChild(document.getElementById("evernoteGmailScript"));';document.body.appendChild(a)};
Object.preventExtensions(this)}Object.preventExtensions(GmailClipper);
